Multiple updates
ethereum-optimism/community-hub pull request #153
Opened 2021-08-17 21:05 UTC by qbzzt

Closes OP-1148
Closes OP-1170
Closes OP-1189
Closes OP-1226

2021-08-17 22:40 UTC, gigamesh commented on src/docs/developers/fees.md
> +L1 gas price goes up or down, or if a transaction that fails in the current
"or if a transaction that fails in the current state were successful"

did you mean "or if a transaction that fails if the current state were successful"?

2021-08-17 22:40 UTC, gigamesh commented on src/docs/developers/fees.md
> +    console.log(`  (5) gas price: ${gasPrice.toString()} wei/gas`)
are these supposed to be vertically aligned?

2021-08-17 22:47 UTC, gigamesh commented on src/docs/developers/fees.md
> +        l2GasPrice: l2GasPrice,
I found this section to be confusing until I realized that you're explaining multiple lines in a single object that is getting passed to `encode`.  Maybe it would be better to add your explanations as code comments? Or alternatively, add ellipses at the start and/or end of the code snippets to indicate that they're part of a longer block?

2021-08-17 22:52 UTC, gigamesh commented on src/docs/developers/fees.md
> +    console.log(`coreUtils gasLimit: ${encoded}`)
Maybe include this, to make it explicit? 
```
console.log(`tx cost: ${encoded * 0.015}` gwei)
```

2021-08-17 22:54 UTC, gigamesh commented on src/docs/developers/fees.md
> +At writing `l2GasPrice` on the Optimistic Ethereum is a million. Every 10^5
I would recommend removing the "the" ("on Optimistic Ethereum") since that's how we've been referring to it everywhere else

2021-08-17 22:57 UTC, gigamesh commented on src/docs/developers/fees.md
> +cost 0.015 gwei.
I gotta admit I'm pretty confused by this paragraph. If there is a way to make it clearer, I think that would help a lot.:)

2021-08-17 22:59 UTC, gigamesh commented on src/docs/developers/fees.md
> +([click here for a graph](https://ycharts.com/indicators/ethereum_average_gas_price)). This means that teb thousand units of L2
typo (teb => ten)

2021-08-17 23:15 UTC, K-Ho requested changes
I think some of the fee section needs to be revised. I think we should consider only including the section on "Estimating costs locally" in our own README for core-utils and remove from our docs. I'm worried users/developers will read this and think this is how they're supposed to estimate fees, when in reality this is only in the rare case where they don't want to use `estimateGas` and is very confusing...

2021-08-17 23:15 UTC, K-Ho commented on src/docs/developers/fees.md
> +The `l2GasPrice` is normally a million, but it could rise at times of
"a million" is vague here - 0.001 gwei

2021-08-17 23:15 UTC, K-Ho commented on src/docs/developers/fees.md
> +Sometimes it is advantageous to run the gas estimate locally instead of asking
you're not actually running the gas estimate locally, rather you are manually calculating a fee to pay to set your `tx.gasLimit` - the big use case here is if you want to hardcode an L2 gas limit

2021-08-17 23:15 UTC, K-Ho commented on src/docs/developers/fees.md
> +Sometimes it is advantageous to run the gas estimate locally instead of asking
This fee scheme is planned to be revised in the next release (October), so my gut is this may just be confusing for most users, especially if it's not something lots of users are asking about in discord

2021-08-17 23:15 UTC, K-Ho commented on src/docs/developers/fees.md
> +transaction cost. This works out to `0.045 ¢`, a negligible cost.
Not sure where this number is coming from 😅 -  the l2 gas price can be arbitrarily large under times of congestion. I think you may be thinking the l2 gas price is capped at .015 gwei, but today under congestion, we have l2 gas prices reaching up to 2 gwei. This was  ~10 cents per 10k L2 gas

2021-08-17 23:50 UTC, qbzzt commented on src/docs/developers/fees.md
> +Sometimes it is advantageous to run the gas estimate locally instead of asking
OK. Comment this whole section out.

2021-08-17 23:52 UTC, qbzzt commented on src/docs/developers/fees.md
> +transaction cost. This works out to `0.045 ¢`, a negligible cost.
It came from repeatedly running the estimating code. But you're right, I'll just remove this section too.

2021-08-17 23:53 UTC, qbzzt commented on src/docs/developers/fees.md
> +([click here for a graph](https://ycharts.com/indicators/ethereum_average_gas_price)). This means that teb thousand units of L2
You're right, but I'm just commenting out the whole section.

2021-08-17 23:59 UTC, qbzzt commented on src/docs/developers/fees.md
> +        l2GasPrice: l2GasPrice,
I'll change them to comments.

2021-08-18 00:08 UTC, qbzzt commented on src/docs/developers/fees.md
> +    console.log(`  (5) gas price: ${gasPrice.toString()} wei/gas`)
No, the (4) and (5) are supposed to refer to the transaction cost, which is why they are indented as part of it. However, if it's not clear to you it won't be clear to others either. So I'll align them.

2021-08-18 00:26 UTC, gigamesh approved these changes

2021-08-18 00:31 UTC, gigamesh approved these changes

2021-08-18 00:35 UTC, merged