Added the Getting Started guide
ethereum-optimism/community-hub pull request #182
Opened 2021-09-10 03:55 UTC by qbzzt

2021-09-17 23:58 UTC, K-Ho requested changes
Great first draft!! Have a few comments. Generally want to make this absolutely fool proof :)

2021-09-17 23:58 UTC, K-Ho commented on src/docs/users/getting-started.md
> +The Optimistic Ethereum scaling solution lets you run transactions, similar to Ethereum, but
```suggestion
The Optimistic Ethereum network lets you send transactions, similar to Ethereum, but
```

2021-09-17 23:58 UTC, K-Ho commented on src/docs/users/getting-started.md
> +* Much lower transaction fees. L1 gas cost only affects the cost to write the transaction to L1
I think this is too deep into the weeds. I would just say that transaction fees are between 10x-100x cheaper than fees on mainnet L1 Ethereum.

2021-09-17 23:58 UTC, K-Ho commented on src/docs/users/getting-started.md
> +* Much lower transaction fees. L1 gas cost only affects the cost to write the transaction to L1
I do like linking to the grafana though to give people a sense of the current fees

2021-09-17 23:58 UTC, K-Ho commented on src/docs/users/getting-started.md
> +
The third advantage is decentralization. "All transactions are posted to L1 Ethereum, inheriting the strong security guarantees of Ethereum"

2021-09-17 23:58 UTC, K-Ho commented on src/docs/users/getting-started.md
> +
I would make a note that users must first acquire assets on L1 Ethereum. We should link out to a guide for people to purchase ETH via CEX and then migrate to a Metamask Wallet if they do not have assets on L1 Ethereum yet.

Guide that we link out to should include: 
Purchase ETH through any centralized Exchange, some examples being Coinbase, Gemini, Binance. They will then need to set up a wallet, then withdraw ETH from CEX to your wallet.

2021-09-17 23:58 UTC, K-Ho commented on src/docs/users/getting-started.md
> +them using [a bridge](/docs/users/apps.html#gateways-and-bridges). For depositing ETH, the best
```suggestion
them from Mainnet Ethereum using [a bridge](/docs/users/apps.html#gateways-and-bridges). For depositing ETH, the best
```

2021-09-17 23:58 UTC, K-Ho commented on src/docs/users/getting-started.md
> +   <img src="../../assets/docs/users/getting-started/deposit.png" alt="Deposit form" width="50%">
I would strongly prefer to have this be a gif or a sequencer of screenshots with outline boxes instead. The A, B, C, and D are not beginner friendly.

2021-09-17 23:58 UTC, K-Ho commented on src/docs/users/getting-started.md
> +   <img src="../../assets/docs/users/getting-started/hop.png" alt="Hop form" width="50%">
Again would prefer if this was a Gif or sequencer of images. Not a huge fan of the A,B,C,D

2021-09-17 23:58 UTC, K-Ho commented on src/docs/users/getting-started.md
> +1. Browse to [Hop.Exchange](https://app.hop.exchange/send?sourceNetwork=optimism&destNetwork=mainnet&token=USDC).
Glad we're using hop here!

2021-09-17 23:58 UTC, K-Ho commented on src/docs/users/getting-started.md
> +   <img src="../../assets/docs/users/getting-started/uniswap.png" alt="Uniswap form" width="50%">
Same note as the others would prefer if this was a Gif or sequencer of images.

2021-09-17 23:58 UTC, K-Ho commented on src/docs/users/getting-started.md
> +
Something we're missing here is "Switching your wallet to connect to Optimstic Ethereum": see https://chainid.link/?network=optimism. A TODO in the future is to have a tutorial page that shows how to connect to Optimistic Ethereum on different top wallets, since many other wallets like Coinbase wallet allow you to actually select the network in your settings

2021-09-24 16:15 UTC, qbzzt commented on src/docs/users/getting-started.md
> +
I already tell them this will happen (step 6) because the app asks for the network switch. I assume they are using the same wallet they used initially, so if we're going to explain this more deeply we should do it in the Uniswap section, step 2. In Metamask you just need to approve it.

How about we publish this as-is and I'll write a "how to connect your wallet to Metamask" tutorial, probably on Monday?

2021-09-29 03:10 UTC, K-Ho approved these changes

2021-09-29 03:10 UTC, merged