20210923 changes
ethereum-optimism/community-hub pull request #204
Opened 2021-09-23 17:16 UTC by qbzzt

* Put a special notice on pages that are OVM 1.0 or OVM 2.0 specific
* Update that `ORIGIN` is now supported
* Update the mainnet white listing page
* Update the new fees with the completed code snippet

Closing: INT-179, INT-178, INT-177, INT-176

2021-09-26 21:28 UTC, K-Ho approved these changes
looks gret

2021-09-26 22:05 UTC, merged

2021-09-27 11:51 UTC, elenadimitrova requested changes

2021-09-27 11:51 UTC, elenadimitrova commented on src/docs/users/fees-2.0.md
> +1. **L2 execution fee**. This fee is `tx.gasLimit * l2gasUsed`,
This is wrong as fees are amount * price not amount * amount. Also this entire page is also duplicated in https://community.optimism.io/docs/developers/l2/new-fees.html#for-users section. I don't mind which one we keep as long as there's only a single location. It can still be referenced elsewhere if needed in multiple places

2021-09-27 11:51 UTC, elenadimitrova commented on src/docs/developers/l2/new-fees.md
> +
Unnecessary empty lines left

2021-09-27 11:51 UTC, elenadimitrova commented on src/docs/developers/l2/contracts-2.0.md
> +const contract = getL2ContractData().L2StandardBridge; // or whatever contract
There is no `L2StandardBridge` property there, see https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts/src/contract-data.ts#L125