Rewrote the gateway tutorial
ethereum-optimism/community-hub pull request #223
Opened 2021-10-04 19:52 UTC by qbzzt

Closing: #220, INT-215

2021-10-05 16:04 UTC, elenadimitrova requested changes

2021-10-05 16:04 UTC, elenadimitrova commented on src/docs/users/withdrawal.md
> +   * Search the transaction hash on
We are close to merging the [self withdrawals on the gateway](https://github.com/ethereum-optimism/frontends/pull/239)(maybe later today or tomorrow) and I'd really like this tutorial to follow that path instead of Etherscan's relayer.

2021-10-05 16:17 UTC, qbzzt commented on src/.vuepress/config.js
> -            '/docs/users/gateway.md',
I think there is at least one direct link to https://community.optimism.io/docs/users/gateway.html on https://gateway.optimism.io/. Until that link is updated, it is necessary to preserve `gateway.md` and the images it uses.

2021-10-05 16:46 UTC, qbzzt commented on src/docs/users/deposit.md
> +   C. The amount is possible. Click **MAX** to see the maximum amount
You're right, as usual.

2021-10-05 16:52 UTC, qbzzt commented on src/docs/users/withdrawal.md
> +   * Search the transaction hash on
OK, tell me when it's merged and I'll update then.

2021-10-06 02:05 UTC, qbzzt commented on src/docs/users/withdrawal.md
> +   * Search the transaction hash on
And I described it.

2021-10-06 14:25 UTC, elenadimitrova requested changes

2021-10-06 14:25 UTC, elenadimitrova commented on src/docs/users/withdrawal.md
> +   which in case of outage may be later than when you initiate the withdrawal.
"may be later than when you initiate the withdrawal" -> "may be more than 7 days later from when you initiated the withdrawal"

2021-10-06 14:25 UTC, elenadimitrova commented on src/docs/users/withdrawal.md
> +1. [Finalize the transaction](#finalize-the-withdrawal)
Can we replace all instances of "finalize the transaction" with "claim the withdrawal". @SmitV you are now using "claim" consistently across the gateway right and no other variations?

2021-10-06 14:25 UTC, elenadimitrova commented on src/docs/users/withdrawal.md
> +### Finalize the withdrawal
Finalize => claim

2021-10-06 14:25 UTC, elenadimitrova commented on src/docs/users/withdrawal.md
> +1. There are several ways to see if your withdrawal is ready to be finalized:
This entire section describing what should happen when you are waiting should be its own section since at the [beginning of this page](https://github.com/ethereum-optimism/community-hub/pull/223/files#diff-2f5ad2f453a5a2edf066cb1068e07bfb34d2a833441b4349ce5a784dfa5a842fR55) you are describing this as a 3-step process (initiate, wait, claim) yet we have 2 sections (initiate and claim). Best to add a section on waiting to be consistent.

2021-10-06 18:31 UTC, qbzzt commented on src/docs/users/withdrawal.md
> +1. There are several ways to see if your withdrawal is ready to be finalized:
Done

2021-10-06 19:06 UTC, qbzzt commented on src/docs/users/withdrawal.md
> +    amortized over a larger pool of tokens, so the relative cost of the
Done

2021-10-06 19:07 UTC, qbzzt commented on src/docs/users/withdrawal.md
> +     you want to deposit your entire balance.
Done

2021-10-06 19:13 UTC, qbzzt commented on src/docs/users/withdrawal.md
> +   which in case of outage may be later than when you initiate the withdrawal.
In context that would be:

> Note that the seven days are counted from the point the transaction is published on L1. In the case of an which in case of outage may be more than 7 days later from when you initiated the withdrawal

Which would be incorrect (because the point when it is published to L1 is not necessarily more than seven days from when you initiate the withdrawal). So instead I wrote

> Wait the verification challenge period, which is seven days from the time the transaction is published on L1.
>
> Normally transactions are published on L1 quickly, but in the case of an outage it might take longer, in which case it will take longer until you can claim your withdrawal.

2021-10-07 06:56 UTC, elenadimitrova approved these changes

2021-10-07 10:27 UTC, merged