Added the fees for L1<->L2 messages
ethereum-optimism/community-hub pull request #246
Opened 2021-11-05 21:19 UTC by qbzzt

2021-12-01 11:25 UTC, Nicca42 requested changes

2021-12-01 11:25 UTC, Nicca42 commented on src/docs/developers/bridge/fees.md
> +For an L1 to L2 transaction the major fee is the L1 cost of submitting the transaction. You send a transaction to the [`L1CrossDomainMessenger`](https://github.com/ethereum-optimism/optimism/blob/reg
...the majority of the cost is the L1 fee for submitting the transaction

2021-12-01 11:25 UTC, Nicca42 commented on src/docs/developers/bridge/fees.md
> +:::
Remove this tip.

2021-12-01 11:25 UTC, Nicca42 commented on src/docs/developers/bridge/fees.md
> +contract, which then sends a call to the [`CanonicalTransactionChain`](https://github.com/ethereum-optimism/optimism/blob/regenesis/0.5.0/packages/contracts/contracts/L1/rollup/CanonicalTransactionCh
...but is ultimately determined by L1 gas costs.

2021-12-01 11:25 UTC, Nicca42 commented on src/docs/developers/bridge/fees.md
> +1. An L1 transaction that *finalizes* the transaction, after the verification challenge period (one week on mainnet) has passed. This transaction is somewhat expensive because it includes verifying a
An L1 transaction that *finalizes* the transaction. This transaction can only be submitted after the verification challenge period (one week on mainnet) has passed.

2021-12-01 11:25 UTC, Nicca42 commented on src/docs/developers/bridge/fees.md
> +1. An L1 transaction that *finalizes* the transaction, after the verification challenge period (one week on mainnet) has passed. This transaction is somewhat expensive because it includes verifying a
I don't like the way we are explaining the challenge period, but I cannot think of a better way. I want it to be something like: one week from initialisation, but I can't figure out how to squeeze that into the sentence. Might need to be broken up more.

2021-12-01 21:31 UTC, qbzzt commented on src/docs/developers/bridge/fees.md
> +1. An L1 transaction that *finalizes* the transaction, after the verification challenge period (one week on mainnet) has passed. This transaction is somewhat expensive because it includes verifying a
What about now? I just linked to where we explain it.

2022-01-05 14:19 UTC, elenadimitrova commented on src/.vuepress/config.js
> +                '/docs/developers/bridge/fees.md'
Can we rename this page to `cross-domain-fees` as we had a single `fees` page before whereas now we have this plus `transaction-fees` under dev docs.

2022-01-05 14:38 UTC, elenadimitrova approved these changes

2022-01-05 14:38 UTC, merged