feat: add known issues page
ethereum-optimism/community-hub pull request #282
Opened 2021-12-03 21:53 UTC by smartcontracts

**Description**
Adds a "known issues" page for the purpose of distributing information about known bugs. Adds an entry to that page for the gas pricing discrepancy that we found w/r/t warm and cold storage slots.

**Metadata**
- Fixes INT-366

2021-12-03 23:14 UTC, Nicca42 commented
Just want to confirm @smartcontracts that the only way this issue is triggered is `transfer`s and hardcoded gas forwarding?

2021-12-04 01:12 UTC, smartcontracts commented
> Just want to confirm @smartcontracts that the only way this issue is triggered is `transfer`s and hardcoded gas forwarding?

Correct, this is the only way I know of right now

2021-12-04 16:03 UTC, Nicca42 requested changes

2021-12-07 15:12 UTC, Nicca42 approved these changes

2021-12-07 15:13 UTC, merged