Started useful dev tools section
ethereum-optimism/community-hub pull request #287
Opened 2021-12-10 21:56 UTC by Nicca42

Updates the "Infrastructure" section to "Useful Tools for Developers"

Pulls in many of the pages from @smartcontracts strawman rewrite.

2022-01-05 14:22 UTC, elenadimitrova commented on src/.vuepress/config.js
> +            '/docs/useful-tools/providers.md',
I think @smartcontracts called this section `build`, rather than `useful-tools`, perhaps use that?

2022-01-05 22:36 UTC, smartcontracts requested changes

2022-01-05 22:36 UTC, smartcontracts commented on src/docs/build/debugging.md
> +
Actually I changed my mind, let's add back in the section about Etherscan. Here's a blurb you can use:

```
## Etherscan

We have Etherscan explorers for the [Optimism mainnet](https://optimistic.etherscan.io) and the [Optimism Kovan testnet](https://kovan-optimistic.etherscan.io).
Etherscan has lots of tools to help you debug transactions.

Optimistic Etherscan has all the tools you expect from Etherscan, such as:
- [Detailed transaction information](https://optimistic.etherscan.io/tx/0x292423266d6da24126dc4e0e81890c22a67295cc8b1a987e71ad84748511452f)
- [List of events emitted by a transaction](https://optimistic.etherscan.io/tx/0x292423266d6da24126dc4e0e81890c22a67295cc8b1a987e71ad84748511452f#eventlog)
- [Contract source code and verification](https://optimistic.etherscan.io/address/0x420000000000000000000000000000000000000F#code)
- And everything else you might find on Etherscan!

It's also got some Optimism-specific features:
- [A list of L1-to-L2 transactions](https://optimistic.etherscan.io/txsEnqueued)
- [A list of L2-to-L1 transactions](https://optimistic.etherscan.io/txsExit)
- [A tool for finalizing L2-to-L1 transactions](https://optimistic.etherscan.io/messagerelayer)
- And more! Just check it out and click around to find all of the available features.
```

2022-01-05 22:36 UTC, smartcontracts commented on src/docs/build/explorers.md
> +### Optimistic Ethereum (mainnet)
Lots of references to Optimistic Ethereum and Optimistic Kovan in this PR that need to be changed to Optimism and Optimism Kovan.

2022-01-05 22:36 UTC, smartcontracts commented on src/.vuepress/config.js
> -const { description } = require('../../package')
I think it'd be better to remove this linting fix only because the style PR (#311) modifies the configuration file and I'd rather not have to deal with weird merge conflicts. I think better to lint as a last step once these content PRs are merged, then add checks into CI that force us to lint going forward.

2022-01-05 22:36 UTC, smartcontracts commented on src/docs/build/debugging.md
> +
Potentially this content go into the `explorers.md` page and we can link out to that other page from this page.

2022-01-05 22:36 UTC, smartcontracts commented on src/docs/build/monitoring.md
> +[Optimism](https://optimism.io) has an [instatus Status page](https://optimism.instatus.com/). This page includes public APIs, the gateway, deposits, withdraws and transaction sequencing for both Opt
```suggestion
Check out the [Optimism status page](https://optimism.instatus.com/).
This page includes public APIs, the gateway, deposits, withdraws and transaction sequencing for both Optimism mainnet and Optimistic Kovan.
```

2022-01-05 22:36 UTC, smartcontracts commented on src/.vuepress/config.js
> +            "Running a Network Node",
We can remove this link. We have a separate page in the dev docs now that explains how to run a testnet or mainnet node.

2022-01-06 19:38 UTC, smartcontracts commented on src/docs/build/networks.md
> +We recently removed our whitelist! This means that anyone can deploy onto Optimism. However, if you want support getting live on Optimism, or if you want some PR hype you can apply [here](https://opt
```suggestion
We recently removed our whitelist! This means that anyone can deploy onto Optimism. However, if you want support getting live on Optimism, or if you want some PR hype you can apply [here](https://optimismpbc.typeform.com/get-in-touch).
```

2022-01-06 19:38 UTC, smartcontracts commented on src/docs/build/networks.md
> +This is our **test** network. To get test Kovan ETH as well as OETH, check out our [faucets page](./faucets.md).
Trying to avoid using the term `OETH`, ideal if it's just "ETH" but on both systems. I think better if we do something like "To get ETH on Kovan and Optimism Kovan, checkout ...".

2022-01-06 19:38 UTC, smartcontracts commented
Requesting a few final minor changes

2022-01-07 10:34 UTC, Nicca42 commented
Done. Let me know if there is anything else, otherwise this is good to go.

2022-01-07 14:22 UTC, smartcontracts approved these changes
One small nit, otherwise LGTM

2022-01-07 14:22 UTC, smartcontracts commented on src/.vuepress/config.js
> +        ['https://www.optimism.io/apps/tools', 'Third Party Tools on OE'],
```suggestion
        ['https://www.optimism.io/apps/tools', 'Third Party Tools'],
```

2022-01-07 14:27 UTC, merged