Fixed reference for fee docs, ethers interaction
ethereum-optimism/community-hub pull request #288
Opened 2021-12-13 15:35 UTC by Nicca42

Reference fee code did not call ethers correctly.

2021-12-13 15:45 UTC, elenadimitrova approved these changes

2021-12-13 15:57 UTC, K-Ho commented on src/docs/developers/l2/new-fees.md
> +      const OVM_GasPriceOracle = ethers.getContractFactory('OVM_GasPriceOracle')
we're using `getContractFactory` from `@eth-optimism/contracts`

2021-12-13 15:57 UTC, K-Ho requested changes
Needs some changes

2021-12-13 15:57 UTC, K-Ho commented on src/docs/developers/l2/new-fees.md
> +      const serializedTx = ethers.utils.serializeTransaction({
https://github.com/ethereum-optimism/optimism/blob/b7e9d10c77b554f6635aa0ef698be46e8991ffde/integration-tests/test/fee-payment.spec.ts#L7 - I think it's actually  
```
import { serialize } from '@ethersproject/transactions'
```

2021-12-14 15:54 UTC, K-Ho requested changes
one more fix

2021-12-14 15:54 UTC, K-Ho commented on src/docs/developers/l2/new-fees.md
>        import { ethers } from 'ethers'
```suggestion
      import { Contract } from 'ethers'
```

2021-12-14 23:36 UTC, K-Ho approved these changes

2021-12-14 23:36 UTC, merged