Wallet Developer's guide - first draft
ethereum-optimism/community-hub pull request #307
Opened 2021-12-22 14:22 UTC by qbzzt

The first draft, as requested in https://www.notion.so/optimismpbc/Wallet-Developers-97578a89b27c4af88f77b0021edb3807.

Closing: INT-288

2021-12-22 14:46 UTC, elenadimitrova reviewed
LGTM except for a few small picks but @K-Ho to review as well.

2021-12-22 14:46 UTC, elenadimitrova commented on src/docs/developers/by-role/wallet-dev.md
> +- [`wallet_switchEthereumChain`](https://eips.ethereum.org/EIPS/eip-3326)
Open any external links in a new tab.

2021-12-22 14:46 UTC, elenadimitrova commented on src/docs/developers/by-role/wallet-dev.md
> +A user can add or swithc into a chain using either the wallet's user interface or a dapp's user interface. To enable switching on a dapp, the wallet needs to handle these requests:
typo -> swithc

2021-12-22 14:46 UTC, elenadimitrova commented on src/docs/developers/by-role/wallet-dev.md
> +1. Connect to one chain at a time, the way MetaMask does it. Let the user switch chains either from your user interface, or through a user interface.
Fix this sentence -> Let the user switch chains either from your user interface, or through a user interface.

2021-12-22 14:46 UTC, elenadimitrova commented on src/docs/developers/by-role/wallet-dev.md
> +You connect to Optimism the same way you do to Ethereum, by connecting to a JSON RPC endpoint. However, the currently supported fork for Optimism is [Berlin](https://eth.wiki/roadmap/berlin), not [Lo
Open external links in new tab.

2021-12-22 15:45 UTC, qbzzt commented on src/docs/developers/by-role/wallet-dev.md
> +- [`wallet_switchEthereumChain`](https://eips.ethereum.org/EIPS/eip-3326)
That is handled by Vuepress. If you look at our other docs (for example, https://raw.githubusercontent.com/ethereum-optimism/community-hub/main/src/docs/infra/monitoring.md), all external links are in this format.

2021-12-23 08:12 UTC, K-Ho requested changes
looks good! A couple requested changes but looking great.

2021-12-23 08:12 UTC, K-Ho commented on src/docs/developers/by-role/wallet-dev.md
> +[Click here for the Optimism endpoints](../../infra/networks.md). You can choose between our public endpoints, which are rate limited, and [endpoints from infrastructure providers](../../infra/networ
Just looked through these links - I think we should add a note in the infra page where it says:
> We also support and maintain the following public RPC endpoints. However, we highly encourage you to set up a private RPC endpoint with any of the above mentioned providers instead. These public endpoints should not be used in production systems.

We ought to include details around "These public endpoints are IP rate limited to ___ requests per IP address per minute".

2021-12-23 08:12 UTC, K-Ho commented on src/docs/developers/by-role/wallet-dev.md
> +The ERC-20 contract address for a token on Optimism may be different from the address for the same token on Ethereum. [The list of tokens and their addresses is here](https://static.optimism.io/optim
can also link to: https://tokenlists.org/token-list?url=https://static.optimism.io/optimism.tokenlist.json

2021-12-23 08:12 UTC, K-Ho commented on src/docs/developers/by-role/wallet-dev.md
> +- **Finalized On-Chain**: This status is only application for L2->L1 transactions, and means that the transaction was finalized on L1 after the verification period has passed.
```suggestion
- **Finalized On-Chain**: This status is only application for L2->L1 transactions, and means that the transaction was finalized on L1 after the seven day verification period has passed.
```

2021-12-23 08:12 UTC, K-Ho commented on src/docs/developers/by-role/wallet-dev.md
> +You can see a summary of the differences [here](../l2/differences.md). These are the differences that are most relevant to wallet developers:
Optional suggestion:  

```suggestion
We aim to be [EVM equivalent](https://medium.com/ethereum-optimism/introducing-evm-equivalence-5c2021deb306), meaning we aim to minimize the differences between Optimism and Ethereum. You can see a summary of the few differences between Optimism and Ethereum [here](../l2/differences.md). These are the differences that are most relevant to wallet developers:
```

2021-12-23 08:12 UTC, K-Ho commented on src/docs/developers/by-role/wallet-dev.md
> +Most of the cost of an Optimism transaction is not the gas consumed by the transaction itself (which is priced in most cases at 0.001 gwei), but the cost of writing the transaction in Ethereum. That
```suggestion
Most of the cost of an Optimism transaction is not the gas consumed by the transaction itself (which is priced at 0.001 gwei when the chain is not congested), but the cost of writing the transaction in Ethereum. That cost is deducted automatically from the user's balance on Optimism.
```
We need to draw more attention to this section because this is the single diff that matters for wallet developers beyond supporting any other EVM equivalent chain (e.g. Polygon). We need to call out explicitly that wallet developers *need to add custom code* to how they normally display fees, since what they usually display is now only the L2 portion of the total fee their user will pay.

2021-12-23 09:07 UTC, qbzzt commented on src/docs/developers/by-role/wallet-dev.md
> +The ERC-20 contract address for a token on Optimism may be different from the address for the same token on Ethereum. [The list of tokens and their addresses is here](https://static.optimism.io/optim
Are you sure? That list isn't really set up for multi-chain tokens (see https://linear.app/optimism/issue/INT-440/the-token-list-ui-is-broken).

2021-12-23 18:46 UTC, qbzzt commented on src/docs/developers/by-role/wallet-dev.md
> +[Click here for the Optimism endpoints](../../infra/networks.md). You can choose between our public endpoints, which are rate limited, and [endpoints from infrastructure providers](../../infra/networ
Apparently they are not rate limited right now. Should I say they are?

2022-01-05 21:51 UTC, K-Ho commented on src/docs/developers/by-role/wallet-dev.md
> +[Click here for the Optimism endpoints](../../infra/networks.md). You can choose between our public endpoints, which are rate limited, and [endpoints from infrastructure providers](../../infra/networ
Believe we resolved this copy in slack

2022-01-05 21:54 UTC, K-Ho commented on src/docs/developers/by-role/wallet-dev.md
> +
My question as a wallet developer would be "How do I track this state of transactions sent through my wallet?" I think the answer right now is probably that we need to wait for the JS SDK for this... 

For now, we can add something like:

"For now, we recommend wallets consider transactions final after they are Sequencer confirmed as there are no reorgs on the chain and there is currently not standard tooling for tracking when transactions are confirmed on chain. We have a JS SDK coming soon that will contain standard tooling to track these three states of each transaction "

2022-01-05 21:57 UTC, K-Ho commented on src/docs/developers/by-role/wallet-dev.md
> +Most of the cost of an Optimism transaction is not the gas consumed by the transaction itself (which is priced at 0.001 gwei when the chain is not congested), but the cost of writing the transaction
Would change language from cost -> transaction fee

E.g. "The majority of an Optimism transaction's fee is not from the gas..."

Reposting my same comment from before:

We need to draw more attention to this section because this is the single diff that matters for wallet developers beyond supporting any other EVM equivalent chain (e.g. Polygon). We need to call out explicitly that wallet developers need to add custom code to how they normally display fees, since what they usually display is now only the L2 portion of the total fee their user will pay.

^I think we can accomplish this by adding a highlight or bold to ensure that wallet developers know that they need to add *custom code* here.

2022-01-05 21:57 UTC, K-Ho requested changes
minor copy changes, and want to really highlight to wallet developers that they need to add custom code for fees. That's 95% of the integration overhead for adding Optimism to a wallet.

2022-01-07 09:45 UTC, elenadimitrova commented on src/.vuepress/config.js
> +            },
The Guides should be a level 1 section as agreed in first scoping call. I'm still split on what we should call them: "Integration guides" or "Developer guides" ? @K-Ho

2022-01-12 16:18 UTC, K-Ho commented on src/docs/guides/wallet-dev.md
> +[You can read more about this subject here](../developers/build/transaction-fees.md). The relevant code sample is [here](../developers/build/transaction-fees.md#displaying-fees-to-users). Typically,
```suggestion
[You can read more about this subject here](../developers/build/transaction-fees.md). The relevant code sample is [here](../developers/build/transaction-fees.md#displaying-fees-to-users). Typically, 95% of the work to integrate Optimism to a wallet is to make sure that users are displayed the correct transaction fee.
```

2022-01-12 16:18 UTC, K-Ho approved these changes

2022-01-13 11:57 UTC, merged