Added an explanation of why address aliasing is important
ethereum-optimism/community-hub pull request #344
Opened 2022-02-05 20:05 UTC by qbzzt

Requested on the Discord.

2022-02-09 00:45 UTC, Nicca42 commented on src/docs/developers/build/differences.md
>  The value of `tx.origin` is determined as follows:
I know you didn't write this section, but could we add a diagram here? This is a bit confusing to follow just in writing.

2022-02-09 00:51 UTC, Nicca42 requested changes
This is a very complex section, so there is going to be a lot of back and forth to get this right.

2022-02-09 00:51 UTC, Nicca42 commented on src/docs/developers/build/differences.md
> +For example, a hacker can fork [Uniswap](https://uniswap.org/) to create their own exchange (on L2), and provide it with liquidity that appears to provide profitable arbitrage opportunities (for exam
Make this a new paragraph please

2022-02-09 00:51 UTC, Nicca42 commented on src/docs/developers/build/differences.md
> +For example, a hacker can fork [Uniswap](https://uniswap.org/) to create their own exchange (on L2), and provide it with liquidity that appears to provide profitable arbitrage opportunities (for exam
Actually this example is a bit too complex to do like this. Can we turn this into an ordered list? e.g

1. The hacker makes a contract on L2 at the same address as...

2022-02-09 00:51 UTC, Nicca42 commented on src/docs/developers/build/differences.md
> +The way Optimism actually works, even though the L1 contract has the same address, the address still appears different when it sends a message to L2, so it cannot abuse rights that were given to the
Can we rephrase this? 

Optimism is protected from this because ...

2022-02-09 03:59 UTC, qbzzt commented on src/docs/developers/build/differences.md
>  The value of `tx.origin` is determined as follows:
It doesn't matter **who** wrote the section. I can fix other people's work.

2022-02-09 04:17 UTC, qbzzt commented on src/docs/developers/build/differences.md
>  The value of `tx.origin` is determined as follows:
However, a table might do the job of a diagram at a lot less effort.

2022-02-16 00:10 UTC, Nicca42 requested changes
This is getting very close. Great story explanation, love the names! 😄

2022-02-16 00:10 UTC, Nicca42 commented on src/docs/developers/build/differences.md
> +To prevent this problem the behavior of the `ORIGIN` and `CALLER` opcodes (`tx.origin` and `msg.sender`) differs slightly between L1 and L2.
I'd like to add a lil line + link here to the solidity docs about not using tx.origin. 

https://docs.soliditylang.org/en/latest/security-considerations.html#tx-origin

2022-02-16 00:10 UTC, Nicca42 commented on src/docs/developers/build/differences.md
> +   **Note:** There are actually multiple contracts in Uniswap, so this explanation is a bit simplified.
This is great. Can we move this note to after step 1?

2022-02-16 00:10 UTC, Nicca42 commented on src/docs/developers/build/differences.md
> +1. Nimrod gives the Hackswap contract an allowance of 1000 DAI.
give < approve

2022-02-16 00:10 UTC, Nicca42 commented on src/docs/developers/build/differences.md
> +1. Before Nimrod's transaction reaches the blockchain, a different transaction reaches it from the bridge, one from an L1 contract on the same address as Hackswap.
Before Nimrod's swap transaction is sent to the blockchain, Helena Hacker sends a transaction from an L1 contract with the same address as Hackswap.

2022-02-16 00:10 UTC, Nicca42 commented on src/docs/developers/build/differences.md
> +   However, because Optimism modified the transaction's `tx.origin` (which is also the initial `msg.sender`), the transaction comes from a *different* address, one that does not have the allowance.
Make this a new paragraph. 

Wrap up the narrative with: Nimrod is luckily protected because Op modified...

2022-03-01 18:57 UTC, Nicca42 approved these changes
Amazing!

2022-03-01 18:57 UTC, merged