docs(build/using-tools): add foundry
ethereum-optimism/community-hub pull request #350
Opened 2022-02-14 15:51 UTC by tarrencev

2022-02-15 23:16 UTC, Nicca42 requested changes
Add description + link

2022-02-15 23:16 UTC, Nicca42 commented on src/docs/developers/build/using-tools.md
> +
Please add a 1/2 liner about what foundry is, including a link to the tool.

2022-02-24 01:59 UTC, qbzzt commented on src/docs/developers/build/using-tools.md
> +
"Foundry is a blazing fast, portable and modular toolkit for Ethereum application development written in Rust."

2022-03-01 18:47 UTC, Nicca42 requested changes
Looks good

2022-03-01 18:47 UTC, Nicca42 commented on src/docs/developers/build/using-tools.md
> +Foundry is a blazing fast, portable and modular toolkit for Ethereum application development written in Rust.
Link to this https://www.paradigm.xyz/2021/12/introducing-the-foundry-ethereum-development-toolbox

As they don't seem to have a real website.

2022-03-08 21:29 UTC, Nicca42 approved these changes

2022-03-08 21:29 UTC, merged