Added the fact that L1 gas burned is gone
ethereum-optimism/community-hub pull request #353
Opened 2022-02-15 03:57 UTC by qbzzt

Closing: #352

Also added:
1. The amount of gas burned isn't proportional to `gasLimit`, but `gasLimit - freeGas`
1. How to get the values of the parameters

2022-02-15 23:09 UTC, Nicca42 requested changes

2022-02-15 23:09 UTC, Nicca42 commented on src/docs/developers/bridge/messaging.md
> +To see the current values, [go to Etherscan](https://etherscan.io/address/0x5E4e65926BA27467555EB562121fac00D24E9dD2#readContract) and expand `enqueueL2GasPrepaid` for the free L2 gas amount and `l2G
Can we split this up

1. To see the current values ... 
2. Within this there is the enqueue and the discount, which cover the free & exchange 

Maybe a little description, for each as they are not very intuitive. What does it mean to have a free L2 gas?

2022-03-01 18:40 UTC, Nicca42 requested changes

2022-03-01 18:40 UTC, Nicca42 commented on src/docs/developers/bridge/messaging.md
> +The parameters in the explanation above were 1.92 million and 32 when I wrote it, but they may change in the future.
at time of writing,

2022-03-08 21:41 UTC, Nicca42 requested changes

2022-03-08 21:41 UTC, Nicca42 commented on src/docs/developers/bridge/messaging.md
> +The vast majority of L1 to L2 calls spend less than that on L2, so nothing further is required.
The vast majority of L1 to L2 calls spend less than the 1.92m, so nothing further is required.

2022-03-08 21:41 UTC, Nicca42 commented on src/docs/developers/bridge/messaging.md
> +If you think that your call might spend more than that on L2, you can specify a higher gas limit.
Can we add a sentence like "If you'd like to check how much gas your transaction will use please see our JavaScript SDK gas estimator" Or whatever is most accurate + a link

2022-03-08 21:41 UTC, Nicca42 commented on src/docs/developers/bridge/messaging.md
> +However, to prevent denial of service attacks, we have to impose a cost on higher gas limits.
...cost on gas limits higher than 1.92m

2022-03-08 21:41 UTC, Nicca42 commented on src/docs/developers/bridge/messaging.md
> +For example, if you specify a two million gas limit in the call to `L1CrossDomainMessenger`, it will be processed this way:
Please write 2m not two million, lets keep number formatting consistent here

2022-03-08 21:41 UTC, Nicca42 commented on src/docs/developers/bridge/messaging.md
> +| remaining gas (2,000,000 - 1,920,000) : 80,000 | Burn 2,500 gas on L1 for the 80,000 gas on L2 (80,000/32) |
This ordering is confusing. Also please update number formatting to be consistant. 

| remaining gas (1.92m - 2m) | ...

What is the 80k? It is not clear.

2022-03-08 21:41 UTC, Nicca42 commented on src/docs/developers/bridge/messaging.md
> +| remaining gas (2,000,000 - 1,920,000) : 80,000 | Burn 2,500 gas on L1 for the 80,000 gas on L2 (80,000/32) |
2 500 gas is spent on the L1 portion of the gas fee, while the remaining 80 000 gas is used for the L2 gas fee. This is inline with the 1:32 ratio of gas.

2022-03-08 21:41 UTC, Nicca42 commented on src/docs/developers/bridge/messaging.md
> +This is prior to the message being sent to L2, let alone the message being processed.
This is before the message has been sent to the L2, and as such there is no way to know how much L2 gas will actually be used.

2022-03-08 21:41 UTC, Nicca42 commented on src/docs/developers/bridge/messaging.md
> +For example, if the call above with a gas limit of two million only takes ten thousand gas on L2, the 2,500 gas on L1 is still burned.
Put this on a new line.

2022-03-15 03:15 UTC, qbzzt commented on src/docs/developers/bridge/messaging.md
> +If you think that your call might spend more than that on L2, you can specify a higher gas limit.
Yes, but let's do this after that tutorial (https://github.com/ethereum-optimism/optimism-tutorial/pull/89) is merged. I'm going to leave this unresolved to remind me to do that once it's merged.

2022-03-17 12:24 UTC, merged