feat(releases): Added the releases page
ethereum-optimism/community-hub pull request #363
Opened 2022-03-03 18:27 UTC by qbzzt

2022-03-04 16:44 UTC, Nicca42 requested changes

2022-03-04 16:44 UTC, Nicca42 commented on src/docs/developers/releases.md
> +
Please add a line here that if you run your own node you need to subscribe to the RSS feed in order to ensure your node is up to date.

2022-03-05 03:49 UTC, qbzzt commented on src/docs/developers/releases.md
> +
Either the RSS feed or the e-mail.

2022-03-18 13:43 UTC, Nicca42 approved these changes

2022-03-18 13:57 UTC, merged