feat(sdk): Page on the topic
ethereum-optimism/community-hub pull request #382
Opened 2022-04-06 20:59 UTC by qbzzt

As requested by bobbie

Closing: INT-577

2022-04-11 11:24 UTC, Nicca42 requested changes

2022-04-11 11:24 UTC, Nicca42 commented on src/docs/sdk/README.md
> +
Please add a good 2/3 sentences explaining the following points. Remember, this will be the first time a lot of devs find out we have an SDK, so you need to add more context. Ideally it should be able to remain unchanged between versions so try keep it general. The feature list we can update with versions, but lets try keep it high level and not get into specifics that might change. 

1. Why you'd need the SDK
2. Basic feature set (i.e the SDK can help you trace the status of a message getting relayed etc) 
3. Where to go if they find bugs/have feature requests (discord/PRs/bug reports on github) 
4. Calling out where the most up to date info can be found

Then we get into all the tutorials & links.

2022-04-11 11:24 UTC, Nicca42 commented on src/docs/sdk/README.md
> +1. [Communicating with the contracts directly](https://github.com/ethereum-optimism/optimism/tree/develop/packages/contracts/docs)
Add more details here rather than just a list. Basic pros/cons of using each method.

2022-04-11 11:24 UTC, Nicca42 commented on src/docs/sdk/js-client.md
> +There are a few areas in which Optimism requires processing that is different from the Ethereum default:
There are a few areas in which the SDK can help you navigate the differences between Optimism and Ethereum (link to differences): 

...

2022-04-11 11:24 UTC, Nicca42 commented on src/docs/sdk/js-client.md
> +
Outside of the mentioned differences, the SDK can make interacting with Optimism easier, even for the identical processes (please rephrase, goal here is to say the SDK makes your life easier even for things that are the same in Eth)

2022-04-15 12:05 UTC, Nicca42 requested changes
Just this and we are ready to go!

2022-04-15 12:05 UTC, Nicca42 commented on src/docs/sdk/README.md
> +For example, decentralized applications might need to estimate gas costs.
Please put this on a new line/paragraph.

2022-05-06 12:38 UTC, Nicca42 requested changes

2022-05-06 12:38 UTC, Nicca42 commented on src/docs/sdk/README.md
> +- [Go on our Discord](https://discord.optimism.io), get the developer role (in the **#get-a-role** channel) and then ask in **#dev-support**.
This is the wrong link for Discord. https://discord-gateway.optimism.io/

2022-05-06 12:38 UTC, Nicca42 commented on src/docs/sdk/README.md
> +- [Go on our Discord](https://discord.optimism.io), get the developer role (in the **#get-a-role** channel) and then ask in **#dev-support**.
Also do not need to get the developer role anymore to see the dev support channel

2022-05-06 13:18 UTC, qbzzt commented on src/docs/sdk/README.md
> +- [Go on our Discord](https://discord.optimism.io), get the developer role (in the **#get-a-role** channel) and then ask in **#dev-support**.
I changed the link, but https://discord.optimism.io also works because it redirects. I usually prefer shorter URLs, but in a link it really doesn't matter.

2022-05-18 16:56 UTC, Nicca42 approved these changes
LGTM

2022-05-18 17:18 UTC, merged