feat(strategies): Page created
ethereum-optimism/community-hub pull request #388
Opened 2022-04-16 02:36 UTC by qbzzt

Closing: INT-582

Based on discussion on Discord (https://discord.com/channels/667044843901681675/887914409207414785/964265384645636146)

2022-06-21 12:18 UTC, Nicca42 requested changes

2022-06-21 12:18 UTC, Nicca42 commented on src/docs/developers/bridge/strategies.md
> +| Decentralization  | None
Instead of saying none it should say Centralised

2022-06-21 12:18 UTC, Nicca42 commented on src/docs/developers/bridge/strategies.md
> +| Decentralization  | None
An d possibly instead of saying Decentralization it should say Trust Assumption, but I will leave that up to you.

2022-06-21 12:18 UTC, Nicca42 commented on src/docs/developers/bridge/strategies.md
> +
And even then, you shouldn't.

2022-06-21 12:18 UTC, Nicca42 commented on src/docs/developers/bridge/strategies.md
> +
Add something here, why is this the same decentralization promise? 

You are already trusting Optimism to run the chain, therefore trusting us to relay messages is not adding any additional trust assumptions to your system. (or something like that)

2022-06-21 12:18 UTC, Nicca42 commented on src/docs/developers/bridge/strategies.md
> +| Cost              | Pretty cheap (it's a simple transaction on L1)
Cost | Cheapish (Requires an L1 transaction) 
Trust Assumption | Same as using Optimism

2022-06-21 12:18 UTC, Nicca42 commented on src/docs/developers/bridge/strategies.md
> +| Decentralization  | Nearly full (somebody needs to initiate the claiming transaction)
Trust Assumption | Almost as good as using Optimism, however someone needs to initiate the claim transaction on L1

2022-06-21 12:18 UTC, Nicca42 commented on src/docs/developers/bridge/strategies.md
> +You can also use incentives, for example using a mechanism such as [Uma's](../../useful-tools/oracles/#universal-market-access-uma).
Its UMA's (UMA is an acronym)

2022-06-21 12:18 UTC, Nicca42 commented on src/docs/developers/bridge/strategies.md
> +Otherwise, it's similar to centralized communications, just with a few extra relays that can take over.
> just with a few extra relayers that can take over.

2022-06-21 12:18 UTC, Nicca42 commented on src/docs/developers/bridge/strategies.md
> +However,  this mechanism is only truly decentralized if there are enough relays to make sure there will always be an honest one.
> relayers

2022-07-06 13:46 UTC, Nicca42 commented
There is far too much happening in this PR and I cannot verify everything. Please separate (at the very least) to the following PRs. Pretty sure a lot of these are also very out of date, yet another reason to not make massive PRs. 

* [ ] The caching fix (code owners should be removed, we have already done this have we not?) 
* [ ] Governance 
        The gov images 
        gov overview 
        gov fund 
        economics, everything in the ./governance folder
* [ ] Communication strategies 
* [ ] guides 
* [ ] How optimism works 
* [ ] SDK updates
* [ ] Providers 
* [ ] tutorials

2022-07-06 15:28 UTC, qbzzt commented
Oops. It was supposed to be just one page, but I must have opened a branch off of a branch instead of from `main`. I have since put my branch opening in a script so I won't forget steps.

```sh
#! /bin/bash

echo Adding branch $1

git checkout main
git pull
git branch $1
git checkout $1
git push --set-upstream origin $1
```

I'll save the file that is actually useful and close this.

2022-07-06 15:28 UTC, closed without merging