feat(cheap-dapp): Initial version
ethereum-optimism/community-hub pull request #406
Opened 2022-05-10 19:47 UTC by qbzzt

Closing: INT-596

2022-06-21 13:21 UTC, Nicca42 requested changes

2022-06-21 13:21 UTC, Nicca42 commented on src/docs/developers/build/cheap-dapp.md
> +The worst case for writing to storage (previously uninitialized storage) is a cost of [22100 gas per 32 byte word](https://www.evm.codes/#55), which averages out to less than 700 gas / byte.
Is it a word of byte? Is it not per 32 byte string?

2022-06-21 13:21 UTC, Nicca42 commented on src/docs/developers/build/cheap-dapp.md
> +The worst case for writing to storage (previously uninitialized storage) is a cost of [22100 gas per 32 byte word](https://www.evm.codes/#55), which averages out to less than 700 gas / byte.
Also as we are jumping between L1 and L2 gas here, please specify when you say gas which gas you are referring to. 

> The worst case for writing to storage ~~(previously uninitialized storage)~~ is a cost of [22100 L2 gas per 32 byte word]

2022-06-21 13:21 UTC, Nicca42 commented on src/docs/developers/build/cheap-dapp.md
> +At writing, this means it is cheaper to write a whole kilobyte to storage, rather than add one byte to the transaction call data.
> ~~At writing,~~ This means it is cheaper...

2022-06-21 13:21 UTC, Nicca42 commented on src/docs/developers/build/cheap-dapp.md
> +## Modify the ABI (application binary interface)
> Modify the ABI (Application Binary Interface)

Also link [ABI](https://docs.soliditylang.org/en/develop/abi-spec.html) to definition.

2022-06-21 13:21 UTC, Nicca42 commented on src/docs/developers/build/cheap-dapp.md
> +[It is much more efficient to create a shorter ABI with just the required bytes, and decode it onchain](https://ethereum.org/en/developers/tutorials/short-abi/).
> It is much more efficient to [create a shorter ABI with just the required bytes, and decode it onchain]()

2022-06-21 13:21 UTC, Nicca42 commented on src/docs/developers/build/cheap-dapp.md
> +To get better compatibility, create two contracts:
This feels too specific to the docs, and quite hard to follow in this form. Can we move this to a tutorial? 

Remove everything between 49 and 55, leaving 56: 

> All of your ...

And 48:

> It is much more ...

2022-06-21 13:21 UTC, Nicca42 commented on src/docs/developers/build/cheap-dapp.md
> +This means that the highest amount of ETH we can represent is 2<sup>256</sup>-1 wei, or about 1.2*10<sup>59</sup> ETH.
Should not be talking about ETH and amounts in the same sentence. 

> For example, it is standard to use `uint256` to store values. This means the highest value you can store is 2<sup>256</sup>-1, or about 1.2*10<sup>59</sup>.

2022-06-21 13:21 UTC, Nicca42 commented on src/docs/developers/build/cheap-dapp.md
> +With a total amount of minted ETH around [120 million](https://ycharts.com/indicators/ethereum_supply), this is overkill.
When storing ETH balances using `uint256` is overkill as there is only [120 million ETH](). Thus, we can safely store ETH balances in `uint88` which is just eleven bytes...

2022-06-21 13:21 UTC, Nicca42 commented on src/docs/developers/build/cheap-dapp.md
> +
I do not follow this at all. Are you saying to "cache" in the contracts? Because then you should say store it, not cache. Unless you mean cacheing on the front end? Generally not following.

2022-06-22 04:50 UTC, qbzzt commented on src/docs/developers/build/cheap-dapp.md
> +This means that the highest amount of ETH we can represent is 2<sup>256</sup>-1 wei, or about 1.2*10<sup>59</sup> ETH.
OK. However, I'm not using *store* on purpose. What we're trying to do is reduce the cost of calldata, which is essentially a transmission mechanism.

BTW, 2^256-1 is about 1.2*10^77. The 59 is because of changing from wei to ETH.

2022-06-22 04:53 UTC, qbzzt commented on src/docs/developers/build/cheap-dapp.md
> +To get better compatibility, create two contracts:
I already wrote an article for ethereum.org about this, so I'm reluctant to also write a tutorial that will cover mostly the same ground. But if you think this is too specific we can just remove it here.

2022-07-06 13:38 UTC, Nicca42 requested changes

2022-07-06 13:38 UTC, Nicca42 commented on src/docs/developers/build/cheap-dapp.md
> +As I'm writing this, this means 720 gwei, or 720,000 units of L2 gas.
Please update this

2022-07-06 13:38 UTC, Nicca42 commented on src/docs/developers/build/cheap-dapp.md
> +The worst case for writing to storage (previously uninitialized storage) is a cost of [22100 gas per 32 byte word](https://www.evm.codes/#55), which averages out to less than 700 gas / byte.
^

2022-07-06 13:38 UTC, Nicca42 commented on src/docs/developers/build/cheap-dapp.md
> +At writing, this means it is cheaper to write a whole kilobyte to storage, rather than add one byte to the transaction call data.
^

2022-07-06 13:38 UTC, Nicca42 commented on src/docs/developers/build/cheap-dapp.md
> +[It is much more efficient to create a shorter ABI with just the required bytes, and decode it onchain](https://ethereum.org/en/developers/tutorials/short-abi/).
^

2022-07-06 14:07 UTC, qbzzt commented on src/docs/developers/build/cheap-dapp.md
> +The worst case for writing to storage (previously uninitialized storage) is a cost of [22100 gas per 32 byte word](https://www.evm.codes/#55), which averages out to less than 700 gas / byte.
> Is it a word of byte? Is it not per 32 byte string?

An EVM word is defined as 256 bits, a.k.a. 32 bytes. I'll make that clearer.

2022-08-02 17:39 UTC, qbzzt commented on src/docs/developers/build/cheap-dapp.md
> +For example, when specifying an address in a call from your client to your contract, you can specify that if the value starts with 0x00 the rest of the value is the twenty bytes of an uncached addres
To properly explain this would take an article. I'm going to remove this for now, and write the article for ethereum.org, ok?

2022-08-02 18:37 UTC, Nicca42 commented on src/docs/developers/build/cheap-dapp.md
> +For example, when specifying an address in a call from your client to your contract, you can specify that if the value starts with 0x00 the rest of the value is the twenty bytes of an uncached addres
Works for me

2022-08-02 18:38 UTC, Nicca42 approved these changes

2022-08-02 18:38 UTC, merged