feat(gov-0.1): first version
ethereum-optimism/community-hub pull request #409
Opened 2022-05-18 12:59 UTC by qbzzt

As requested by Bobby (https://optimism-workspace.slack.com/archives/C0214EMUUJ3/p1652828078537819).

2022-05-18 15:25 UTC, Nicca42 requested changes

2022-05-18 15:28 UTC, Nicca42 requested changes

2022-05-18 15:28 UTC, Nicca42 commented on src/.vuepress/config.js
> +        '/docs/developers/bedrock.md',
This should not be in this PR. Please remove.

2022-05-18 19:36 UTC, Nicca42 requested changes

2022-05-18 19:36 UTC, Nicca42 commented on src/docs/governance/gov-01.md
> +Notes:
Can we move this to above the table? Happy to merge after that.

2022-05-18 21:48 UTC, qbzzt commented on src/docs/governance/gov-01.md
> +Notes:
[It's standard to put notes below the table](https://apastyle.apa.org/style-grammar-guidelines/tables-figures/tables). That's where I'd expect them and that's where I think most readers will expect them. Is there a reason not to follow that standard here?

2022-05-19 10:11 UTC, Nicca42 commented on src/docs/governance/gov-01.md
> +Notes:
If that is convention then it's all good, just seems weird to me, but I am no doc expert.

2022-05-19 10:12 UTC, Nicca42 approved these changes
LGTM

2022-05-19 10:12 UTC, merged