fix(*): Updated links to tutorials
ethereum-optimism/community-hub pull request #432
Opened 2022-06-18 16:34 UTC by qbzzt

[Based on Discord](https://discord.com/channels/667044843901681675/921343563596439602/987738042485862440)

2022-06-21 12:05 UTC, Nicca42 commented on src/docs/guides/cex-dev.md
> +As a centralized exchange, there will be times that withdrawals of ETH or an ERC-20 token on a specific chain exceed deposits and you need to transfer assets. To do that you use a bridge or a gateway
You should also add something here before eventually (on a new line) about the standard ERC20 bridge, as in the first sentence you mention it but you do not mention it again. Something like: 

> s a centralized exchange, there will be times that withdrawals of ETH or an ERC-20 token on a specific chain exceed deposits and you need to transfer assets. To do that you use a bridge or a gateway. We have a [standard gateway](https://gateway.optimism.io/) that receives assets on L1 (Ethereum mainnet), and mints the equivalent asset on L2 (which can be Optimism or a different solution). 

> For bridging we have the [Standard ERC20 bridge](https://github.com/ethereum-optimism/optimism-tutorial/tree/main/standard-bridge-standard-token), as well as the [Custom ERC20 bridge](https://github.com/ethereum-optimism/optimism-tutorial/tree/main/standard-bridge-custom-token). 

> Eventually, ...

2022-06-23 03:07 UTC, qbzzt commented on src/docs/developers/tutorials.md
> -* [Bridging Assets with the Optimism SDK](https://github.com/ethereum-optimism/optimism-tutorial/tree/main/cross-dom-bridge)
Thank you for catching this, I'll fix it. The only reason I can think of is that I don't get enough sleep ;-)

2022-06-23 03:58 UTC, qbzzt commented on src/docs/guides/cex-dev.md
> +As a centralized exchange, there will be times that withdrawals of ETH or an ERC-20 token on a specific chain exceed deposits and you need to transfer assets. To do that you use a bridge or a gateway
The two tutorials you linked are both standard bridge, just for different token types. I added a paragraph about adding new tokens to Optimism using them.

2022-07-06 13:31 UTC, Nicca42 requested changes

2022-07-06 13:31 UTC, Nicca42 commented on src/docs/guides/smart-contract-devs.md
> +If you think we need more, you can ask for a specific topic on our [Discord](https://discord.optimism.io/) in the **#doc-requests** channel.
This is not the right Discord link. Please use this: https://discord-gateway.optimism.io/

Also just make sure if we use the wrong one anywhere else.

2022-07-06 14:26 UTC, qbzzt commented on src/docs/guides/cex-dev.md
> +If there is no need for custom business logic, you can [follow the steps in this tutorial](https://github.com/ethereum-optimism/optimism-tutorial/tree/main/standard-bridge-standard-token).
I hate relying on my memory. Do you have a linear ticket you use to track the token repo process? Or a PM who is keeping track of it?

2022-07-06 14:29 UTC, qbzzt commented on src/docs/guides/smart-contract-devs.md
> +If you think we need more, you can ask for a specific topic on our [Discord](https://discord.optimism.io/) in the **#doc-requests** channel.
I'll open another PR for changing it anywhere I `find` it.

2022-07-06 14:41 UTC, qbzzt commented on src/docs/guides/smart-contract-devs.md
> +If you think we need more, you can ask for a specific topic on our [Discord](https://discord.optimism.io/) in the **#doc-requests** channel.
Done. See #446, it should be an easy PR to approve.

2022-07-14 17:14 UTC, Nicca42 commented on src/docs/guides/cex-dev.md
> +If there is no need for custom business logic, you can [follow the steps in this tutorial](https://github.com/ethereum-optimism/optimism-tutorial/tree/main/standard-bridge-standard-token).
Made an issue: https://linear.app/optimism/issue/DOCS-623/update-cex-guide-with-new-token-listing-process

2022-07-14 17:15 UTC, Nicca42 requested changes

2022-07-14 17:15 UTC, Nicca42 commented on src/docs/guides/smart-contract-devs.md
> +If you run into any trouble don't hesitate to ask for help on our [Discord](https://discord.optimism.io/)!
Update link

2022-08-02 14:52 UTC, Nicca42 approved these changes

2022-08-02 14:52 UTC, merged