Governance docs reorg
ethereum-optimism/community-hub pull request #473
Opened 2022-08-24 12:33 UTC by qbzzt

2022-08-25 12:02 UTC, Nicca42 requested changes

2022-08-25 12:02 UTC, Nicca42 commented on src/.vuepress/config.js
> +                '/docs/governance/delegate.md',
Can we move this to being the first page please

2022-08-25 12:02 UTC, Nicca42 commented on src/docs/governance/delegate.md
> +title: Being a Token House delegate
This should be "Become a Token House delegate

2022-08-25 12:02 UTC, Nicca42 commented on src/docs/governance/gov-fund.md
> +title: Governance fund overview
Make caps

2022-08-25 12:02 UTC, Nicca42 commented on src/docs/governance/token-house-history.md
> +title: Token House history
Caps

2022-08-25 12:02 UTC, Nicca42 commented on src/docs/governance/token-house.md
> +title: Token House governance
Caps

2022-08-25 12:02 UTC, Nicca42 commented on src/docs/governance/proposals.md
> +title: Submitting proposals
Caps

2022-08-25 12:02 UTC, Nicca42 commented on src/docs/governance/delegate.md
> +title: Being a Token House delegate
Also Caps

2022-08-25 12:02 UTC, Nicca42 commented on src/docs/governance/citizens-house.md
> +title: Citizens' House governance
Caps

2022-08-25 14:40 UTC, qbzzt commented on src/docs/governance/delegate.md
> +title: Being a Token House delegate
"Become" implies this doesn't include the information for existing delegates, which is not true. How about "Information for Delegates"?

2022-09-20 14:20 UTC, Nicca42 requested changes

2022-09-20 14:20 UTC, Nicca42 commented on src/docs/governance/token-house-history.md
> +### Voting Cycle #5
Please make this a subheading of season 2 (cycle 5) 
reflection period can stay as a high level.

2022-09-20 14:20 UTC, Nicca42 commented on src/docs/governance/token-house-history.md
> +
Add a one-liner here: 

The reflection period was a break between season 1 and season 2 where the Optimism foundation, with the help of delegates and community members, updated and improved the governance process.

2022-09-20 14:20 UTC, Nicca42 commented on src/docs/governance/proposals.md
> +
Please add a tip here: 

This info is here for your convenience. The source of truth for all governance related processes is the OPerating Manual (link).

2022-09-20 14:20 UTC, Nicca42 commented on src/docs/governance/howto-delegate.md
> +   This happens at the start of every voting cycle, which is every three weeks.
This happens at the start of the voting phase in a cycle, which is the last week of each cycle. A new cycle starts every 3 weeks.

2022-09-20 14:20 UTC, Nicca42 commented on src/docs/governance/gov-fund.md
> +The amount of funding for each project was determined by a set of on-chain metrics, calculated via a snapshot of the Optimism chain on April 1, 2022 at 12:00am UTC.
To see live tracking on govFund allocations please see the [Public tracker spreadsheet](https://docs.google.com/spreadsheets/d/1eaHOlWB34ij1KGsXdaNyTQg4tt1Pu2JurJsElBb6a8k/edit#gid=0)

2022-09-20 14:20 UTC, Nicca42 commented on src/docs/governance/howto-delegate.md
> +
I would just link to the section https://github.com/ethereum-optimism/community-hub/pull/473/files#diff-f1c2180dcfc5e0112202d868c037754121d35d92be8cdc0b8e9d04599000527fR18 here where you talk about how to commit. Something like

if you want to become a delegate that others delegate to you need to [state your delegation commitment]()

2022-09-20 14:24 UTC, qbzzt commented on src/docs/governance/token-house-history.md
> +### Voting Cycle #5
Shouldn't it be if anything under **Reflection Point #1**?

2022-09-20 14:48 UTC, qbzzt commented on src/docs/governance/howto-delegate.md
> +
Trevor asked for this change, so I am just adding your sentence.

2022-09-20 14:51 UTC, Nicca42 requested changes

2022-09-20 14:51 UTC, Nicca42 commented on src/docs/governance/token-house-history.md
> +### Special Voting Cycle #2: Dec 1st - Dec 14th, 2022
This needs to be cycle 9 (its messed up your numbers)

2022-09-20 14:51 UTC, Nicca42 commented on src/docs/governance/token-house-history.md
> +* Voting system #9 (Dec 15th, 2022 - Jan 4th, 2023)
Then this is cycle 10

2022-09-20 14:55 UTC, Nicca42 commented on src/docs/governance/token-house-history.md
> +### Voting Cycle #5
hm. No I think we specified it as the first voting cycle of season two. It is to ratify the learnings from the reflection period.

2022-09-20 15:06 UTC, qbzzt commented on src/docs/governance/token-house-history.md
> +### Voting Cycle #5
Then each season starts two weeks earlier. I'll update that.

2022-09-20 15:45 UTC, Nicca42 approved these changes

2022-09-20 15:45 UTC, merged