Updates per convo
ethereum-optimism/community-hub pull request #475
Opened 2022-08-30 00:13 UTC by shelleyolivia

Noted clarifications around the public endpoint and the recommendation for private endpoints given throughput rates.

2022-09-20 23:20 UTC, shelleyolivia commented
@Nicca42 @smartcontracts could I please get a review of this? I made updates based on the Alchemy convos, thanks so much!

2022-09-22 18:30 UTC, Nicca42 requested changes

2022-09-22 18:30 UTC, Nicca42 commented on src/docs/useful-tools/providers.md
> +title: API Providers
Please change this back. Or compromise of:
Node & API Providers

2022-09-24 00:57 UTC, shelleyolivia commented on src/docs/useful-tools/networks.md
> +title: Optimism APIs
Appreciate the context, sg we got feedback that devs look for APIs so I submitted the PR for "Networks, Public RPC Endpoints, & APIs". Thanks Vee!

2022-09-24 01:18 UTC, shelleyolivia commented on src/docs/useful-tools/providers.md
> +title: API Providers
Changed to "Node & API Providers". Thanks Vee!

2022-09-24 01:19 UTC, shelleyolivia commented on src/docs/useful-tools/networks.md
> +::: tip Developer Tip
Done, wasn't clear on that. Thanks Vee!

2022-09-29 17:16 UTC, Nicca42 approved these changes

2022-09-29 17:16 UTC, merged