Update providers.md
ethereum-optimism/community-hub pull request #484
Opened 2022-09-22 13:44 UTC by PolinaShanti

Hello Optimism Team!
 I've added NOWNodes to your provider list.
We provide access to mainnet Optimism node. Developers can use our free API key to test the service and run Optimism full node.  Thank you!

2022-09-22 13:45 UTC, PolinaShanti commented
@Nicca42 @smartcontracts

2022-09-22 13:51 UTC, Nicca42 commented
@qbzzt when you have a moment can you validate this works?

2022-09-27 13:35 UTC, PolinaShanti commented
Hello guys, 
Any news?
Thanks a lot!
@Nicca42 @qbzzt

2022-09-27 16:50 UTC, Nicca42 commented
We are testing, will get back to you when we are done @PolinaShanti

2022-09-27 17:51 UTC, qbzzt commented
I got an API key. But almost all the endpoint tools used in Optimism expect to just use a URL. Is there any way to get a URL with the api key, instead of using https://optimism.nownodes.io with a header field?

2022-09-29 10:03 UTC, PolinaShanti commented
Hi @qbzzt,
Yes, it's possible 
Via GET parameter API_key= your key
Either right after .io/your key

2022-10-03 09:34 UTC, PolinaShanti commented
Hi Team!
@qbzzt were you able to get the API Key into the URL?

2022-10-03 16:37 UTC, qbzzt commented
> Hi Team! @qbzzt were you able to get the API Key into the URL?

Sorry, I have a kid in the hospital so I'm not working is effectively as I normally do.

Anyway, I got it working as https://optimism.nownodes.io/?API_key=<value goes here>
I need to update the PR to make it clearer, I'll do it at some point this week (I'll try to do today).

2022-10-03 22:02 UTC, qbzzt approved these changes
LGTM

2022-10-04 07:20 UTC, PolinaShanti commented
Oh, I'm sorry to hear that. Wish your kid gets well soon!

Thank you so much, Ori!

2022-10-04 12:17 UTC, qbzzt commented
Thank you. She is doing much better now, but it will take a lot rehab and we'll need to figure how to live with her in a wheelchair. Luckily, where we live most places have handicapped accomodations.

2022-10-05 22:54 UTC, Nicca42 requested changes

2022-10-05 22:54 UTC, Nicca42 commented on src/docs/useful-tools/providers.md
> +## NOWNodes
One last change before we get this in, can you move this to the bottom of the list? We've been strict about this in the past and it is only fair to be consistant.

2022-10-05 23:02 UTC, qbzzt commented on src/docs/useful-tools/providers.md
> +## NOWNodes
I moved them up, because I thought we were doing alphabetical order. Do you want me to move it to the bottom?

2022-10-07 17:45 UTC, Nicca42 commented on src/docs/useful-tools/providers.md
> +## NOWNodes
Yes please.

2022-10-07 18:00 UTC, qbzzt commented on src/docs/useful-tools/providers.md
> +## NOWNodes
Done

2022-10-07 18:06 UTC, Nicca42 approved these changes

2022-10-07 18:06 UTC, merged