feat(run-a-node): How to choose whether to sync from L1 or L2
ethereum-optimism/community-hub pull request #519
Opened 2022-10-19 15:58 UTC by qbzzt

Closing: DOCS-687

2022-10-24 15:05 UTC, Nicca42 requested changes

2022-10-24 15:56 UTC, qbzzt commented on src/docs/developers/build/run-a-node.md
> +In OVM 2.0 you choose one of two configurations.
OVM 2.0 is the name of the current version (as distinguished from bedrock). How about I rename it to "pre-Bedrock"?

2022-10-26 07:52 UTC, Nicca42 commented on src/docs/developers/build/run-a-node.md
> +In OVM 2.0 you choose one of two configurations.
Happy with 
pre-bedrock or 
in the current version (learn more about our [next version, Bedrock]())

2022-10-26 12:19 UTC, qbzzt commented on src/docs/developers/build/run-a-node.md
> +In OVM 2.0 you choose one of two configurations.
OK, pre-bedrock (current version) it is.

2022-11-15 22:58 UTC, Nicca42 approved these changes

2022-11-15 22:58 UTC, merged