adding attestation guides
ethereum-optimism/community-hub pull request #525
Opened 2022-10-28 20:19 UTC by sbvegan

**Description**

These documents guide developers through the process of making and reading attestations to the Social Contract.

**Tests**

There are no tests in this PR, but I have a separate repository with a hardhat sandbox that I've verified the scripts work as expected on a local testnet node.

**Additional context**

I worked with the OP team before making this PR.

2022-10-28 20:37 UTC, zainbacchus commented
Lets goo! Excited for this :)

2022-10-31 08:04 UTC, Nicca42 requested changes

2022-10-31 08:04 UTC, Nicca42 commented on src/.vuepress/config.js
> +        text: 'Social Contract',
This should not be a high-level page. It should go under governance. We need to start a new section for retroPGF, so it can go in there.

2022-10-31 21:12 UTC, sbvegan commented on src/.vuepress/config.js
> +        text: 'Social Contract',
Hey @Nicca42 

- I removed the high-level page
- I dropped the, "What is the Social Contract?" doc in a new Retroactive Public Goods Funding section. 
- Because the rest are developer guides, I put them in the "Dev Docs" section under "Social Contract". 
 
What do you think?

2022-10-31 22:03 UTC, sbvegan commented on src/.vuepress/config.js
> +        text: 'Social Contract',
Also, thank you for taking a look and I'm sorry I'm making a mess of this branch :)

2022-11-01 00:43 UTC, qbzzt commented
I think the technical documents belong more under the tutorials. Mind if I edit tomorrow to create a tutorial from it?

2022-11-01 18:54 UTC, qbzzt commented
Do you have SocialContract.sol already running on Optimism Goerli and/or Optimism mainnet? The tutorial requires an address, rather than a TODO to add one.

2022-11-01 20:31 UTC, sbvegan commented
This is the [code](https://github.com/hmrtn/optimism/tree/optimist-nft/packages/contracts-periphery/contracts/universal/op-nft) that was shared with me, alongside some other documents that I don't believe are public. The SocialContract.sol has not been deployed yet, so I just deployed it on local hardhat node to test the scripts. I was asked to make a draft PR to get some initial feedback.

2022-11-01 20:50 UTC, zainbacchus commented
Hey @qbzzt  the contract is being reviewed. Can we get this PR merged in the interim? 

 https://github.com/ethereum-optimism/optimism/pull/3824

2022-11-02 21:48 UTC, qbzzt approved these changes
Ready now, IMAO.

Note: Please merge after https://github.com/ethereum-optimism/optimism-tutorial/pull/137 due to a link to the tutorial.

2022-11-10 07:01 UTC, smartcontracts approved these changes

2022-11-10 07:02 UTC, merged