fix(differences): What to do if you need pre-EIP-155
ethereum-optimism/community-hub pull request #537
Opened 2022-11-07 16:18 UTC by qbzzt

2022-11-10 15:42 UTC, mslipper commented on src/docs/developers/build/differences.md
> +Starting in November 2022, pre-EIP-155 transactions are no longer supported on Optimism through Alchemy.
This should read "on the public endpoint or through Alchemy" to make it super clear which RPCs won't support these transactions.

2022-11-10 16:01 UTC, qbzzt commented on src/docs/developers/build/differences.md
> +Starting in November 2022, pre-EIP-155 transactions are no longer supported on Optimism through Alchemy.
I don't understand this. If I submit a pre-EIP-155 transaction to an Infura endpoint, doesn't it get relayed to our sequencer, which will then reject it? Or is it that the sequencer itself accepts pre-EIP-155 transactions, but the public endpoint is a proxy which doesn't?

2022-11-15 22:55 UTC, Nicca42 commented on src/docs/developers/build/differences.md
> +Just be careful.
Could we add something about why these pre EIP-155 TXs are dangerous?

2022-11-17 19:38 UTC, Nicca42 requested changes

2022-11-17 19:38 UTC, Nicca42 commented on src/docs/developers/build/differences.md
> +For example, you might agree to send me 1 ETH on Georli (chain ID 5) to help me test my contracts.
```suggestion
For example, you might agree to send me 1 ETH on Goerli (chain ID 5) to help me test my contracts.
```

2022-11-17 20:13 UTC, qbzzt commented
When you have an obvious change, such as Georli -> Goerli, you can just do it instead of having me approve it. That way it's not waiting.

2022-11-28 15:12 UTC, Nicca42 approved these changes

2022-11-28 15:12 UTC, merged