feat(navbar): Added a link to project support in help center
ethereum-optimism/community-hub pull request #543
Opened 2022-11-15 13:02 UTC by qbzzt

https://help.optimism.io/hc/en-us/articles/9762044018843-How-do-I-get-project-support-marketing-integrations-etc-

2022-11-15 22:48 UTC, Nicca42 commented
@qbzzt I wanted this info to be native to the docs not just in the user docs.

2022-11-15 22:52 UTC, qbzzt commented
> @qbzzt I wanted this info to be native to the docs not just in the user docs.

I could copy it over. But what would be the benefit? By having it in one place there is just one place to update when things change.

2022-11-15 22:58 UTC, Nicca42 commented
Yea this should be native in the docs.

2022-11-16 02:13 UTC, qbzzt commented
> Yea this should be native in the docs.

With @zainbacchus 's approval, I moved his stuff to a markdown. The style is very different from the one I use. @Nicca42 , your call if it's appropriate here or if I should rewrite it.

2022-11-28 15:24 UTC, Nicca42 requested changes

2022-11-28 15:24 UTC, Nicca42 commented on src/docs/biz/README.md
> +When your project is deployed on Optimism, you’ll be added to [our ecosystem page](https://www.optimism.io/apps/all).
```suggestion
When your project is deployed on Optimism, you can be added to [our ecosystem page](https://www.optimism.io/apps/all). 
```

2022-11-28 15:24 UTC, Nicca42 commented on src/docs/biz/README.md
> +Simply [fill out this form](https://optimismpbc.typeform.com/op-marketing) to be included.
```suggestion
Simply [fill out this form](https://optimismpbc.typeform.com/op-marketing) to be included. Inclusion is at our discretion. 
```

2022-11-28 15:24 UTC, Nicca42 commented on src/docs/biz/README.md
> +We add new projects [here](https://www.optimism.io/apps/all) every week, but you need to deploy first.
```suggestion
We add new projects live on the Optimism mainnet [here](https://www.optimism.io/apps/all) once a week.
```

2022-11-28 15:24 UTC, Nicca42 commented on src/docs/biz/README.md
> +We love to promote values-aligned projects as part of our broader content program.
Do we have our values anywhere publicly?

2022-11-28 15:24 UTC, Nicca42 commented on src/docs/biz/README.md
> +## Grants Funding 🪙🪙
```suggestion
## Governance Grants
```

2022-11-28 15:24 UTC, Nicca42 commented on src/docs/biz/README.md
> +Grants are mainly handled by [The Optimism Collective](https://app.optimism.io/announcement), our open governance system/digital society. If you are interested in seeking funding here, we first recom
```suggestion
Grants are mainly handled by [The Optimism Collective](https://app.optimism.io/announcement), our open governance system/digital society. If you are interested in applying, we first recommend the following: 
```

2022-11-28 15:24 UTC, Nicca42 commented on src/docs/biz/README.md
> +Grants are a lever to support sustainable growth in the ecosystem, therefore we do not provide grants for projects' operational expenses.
Remove this, we are doing something along these lines for season 3. Instead:

Before applying, please check that your application falls within the possible Governance Grant categories in the [OPerating manual](https://github.com/ethereum-optimism/OPerating-manual/blob/main/manual.md#valid-proposal-types).

2022-11-28 15:24 UTC, Nicca42 commented on src/docs/biz/README.md
> +  Check out [our tutorial](https://github.com/ethereum-optimism/optimism-tutorial/tree/main/getting-started) to see how to deploy.
```suggestion
  Check out our [getting started tutorial](https://github.com/ethereum-optimism/optimism-tutorial/tree/main/getting-started) to see how to deploy. We also have [tons of more in-depth tutorials](tutorials) for bridging and other L2 specific functionality. 
```

2022-11-28 15:24 UTC, Nicca42 commented on src/docs/biz/README.md
> +  Demoday is an AMA about your product to our community.
```suggestion
  Demo Day is an AMA about your product to our community. Apply in Discord. 
```

2022-11-28 15:24 UTC, Nicca42 commented on src/docs/biz/README.md
> +- To get reviews in real time from governance delegates go to discord and post about your product in [#temp-check](https://discord.com/channels/667044843901681675/1011238484373159956).
```suggestion
- To get reviews in real time from governance delegates go to discord and post about your project in [#temp-check](https://discord.com/channels/667044843901681675/1011238484373159956).
```

2022-11-28 15:24 UTC, Nicca42 commented on src/docs/biz/README.md
> +(Hint: We give all our sequencer ~100k/day in revenue, away to public goods so your users can rest easy knowing that when they use Optimism, they are contributing to a good cause).
```suggestion
(Hint: We give all our sequencer revenue (~100k/day!), away to public goods so your users can rest easy knowing that when they use Optimism, they are contributing to a good cause). 
```

2022-11-28 15:24 UTC, Nicca42 commented on src/docs/biz/README.md
> +More on Public Goods Funding [here](https://app.optimism.io/announcement), [here](https://medium.com/ethereum-optimism/retroactive-public-goods-funding-33c9b7d00f0c), and [Vitalik’s](https://twitter.
Can we move this to its own page? Then add little one liners about each of these. We really need to have PGF as its own page under the citizen's house.

2022-12-09 15:22 UTC, Nicca42 commented
I'd like to get this in soon ish, we are going to have more eyes looking for support with the retroPGF hype.

2022-12-10 18:56 UTC, qbzzt commented on src/docs/biz/README.md
> +More on Public Goods Funding [here](https://app.optimism.io/announcement), [here](https://medium.com/ethereum-optimism/retroactive-public-goods-funding-33c9b7d00f0c), and [Vitalik’s](https://twitter.
Now that there's a page for it (https://community.optimism.io/docs/governance/retropgf-2/), can we just remove the material from here and link to it?

2022-12-10 19:35 UTC, qbzzt commented on src/docs/biz/README.md
> +More on Public Goods Funding [here](https://app.optimism.io/announcement), [here](https://medium.com/ethereum-optimism/retroactive-public-goods-funding-33c9b7d00f0c), and [Vitalik’s](https://twitter.
If that is acceptable, just approve and merge - I changed it to that link and dealt with everything else.

2022-12-10 19:36 UTC, qbzzt commented
Now that there's a RetroPGF-2 page, I just linked to that.

2022-12-16 11:59 UTC, qbzzt commented
> Why is this PR now modifying all these other files? This PR should not include attestation station stuff. Can we please clean this up or check it is 💯 the latest.

Arrggghhh!!!! It now has over 150 commits. I'm going to close this PR and open a clean one.

2022-12-16 12:10 UTC, closed without merging