feat(how-it-works): Add bedrock
ethereum-optimism/community-hub pull request #548
Opened 2022-11-22 23:23 UTC by qbzzt

Closing: DOCS-583

2022-11-28 15:26 UTC, Nicca42 commented on src/docs/protocol/2-rollup-protocol.md
> +
Nit: do we need so many lines between here?

2022-11-28 15:26 UTC, Nicca42 commented on src/docs/protocol/2-rollup-protocol.md
> +   If the sequencer attempts to ignore a legitimate L1 transaction it ends up with a state that is inconsistent with the verifiers, same as if the sequencer tried to fake the state by other means.
We should have more documentation about forced inclusion that we can point to

2022-11-28 15:28 UTC, Nicca42 approved these changes

2022-11-28 15:28 UTC, Nicca42 commented
@K-Ho can someone working on Bedrock lmk if this is good to go?

2022-11-28 16:04 UTC, qbzzt commented on src/docs/protocol/2-rollup-protocol.md
> +
No. Not that they hurt anything, but I removed them.

2022-11-28 16:21 UTC, qbzzt commented on src/docs/protocol/2-rollup-protocol.md
> +   If the sequencer attempts to ignore a legitimate L1 transaction it ends up with a state that is inconsistent with the verifiers, same as if the sequencer tried to fake the state by other means.
Added.

2022-12-01 18:11 UTC, norswap requested changes

2022-12-01 18:11 UTC, norswap commented on src/docs/protocol/2-rollup-protocol.md
> +1. Wait for the next output root to be submitted to L1 (up to an hour on mainnet, less than that on the test network) then submit the withdrawal proof using `proveWithdrawalTransaction`.
Are we sure about the "up to an hour" bit? (Afaik final values for these haven't been decide for the `SUBMISSION_INTERVAL` value of the `L2OutputOracle` contract, which is what controls this.)

2022-12-01 18:11 UTC, norswap commented on src/docs/protocol/2-rollup-protocol.md
> +   Having the proof available for off-chain testing helps us guard against a whole class of vulnerabilities based on invalid fault proofs.
I would always qualify "proof" as "withdrawal proof" to avoid confusion with "fault proof".

Maybe replace this paragraph by "This new step enables off-chain monitoring of the withdrawals, which makes it easier to identify incorrect withdrawals or output roots."

2022-12-01 19:10 UTC, qbzzt commented on src/docs/protocol/2-rollup-protocol.md
> +   Having the proof available for off-chain testing helps us guard against a whole class of vulnerabilities based on invalid fault proofs.
This is a new feature, which makes extra work for users. I think we need the more detailed explanation of why it is necessary.

2022-12-01 19:16 UTC, qbzzt commented on src/docs/protocol/2-rollup-protocol.md
> +1. Wait for the next output root to be submitted to L1 (up to an hour on mainnet, less than that on the test network) then submit the withdrawal proof using `proveWithdrawalTransaction`.
Thank you. I'll remove the figure for now, but if you could please tell me when it's settled? It's the kind of information developers **need**.

2022-12-01 19:37 UTC, qbzzt commented on src/docs/protocol/2-rollup-protocol.md
> +<details>
For now, yes. People might need Bedrock information or OVM 2.0 information. Once mainnet is Bedrock, I'll remove those.

2022-12-01 20:24 UTC, qbzzt commented on src/docs/protocol/2-rollup-protocol.md
> +   You can read more about it [in the specs](https://github.com/ethereum-optimism/optimism/blob/develop/specs/exec-engine.md#happy-path-sync).
> It's actually the rollup node (not the execution engine) that receives the synchronized blocks and then transmits them to the execution engine.

Are you sure? I assumed we're using geth sync between execution engines because [the spec]https://github.com/ethereum-optimism/optimism/blob/develop/specs/exec-engine.md#happy-path-sync) says so:

> 2. The engine requests headers from peers, in reverse till the parent hash matches the local chain

Can you give me an authoritative answer, and fix the specs if needed?

2022-12-01 20:25 UTC, qbzzt commented on src/docs/protocol/2-rollup-protocol.md
> +You can read more about this [in the specs](https://github.com/ethereum-optimism/optimism/blob/develop/specs/deposits.md).
I think I fixed the explanation. Can you verify the new one is OK?

> Deposit transactions become part of the canonical blockchain in the first L2 block of the "epoch", the L2 blocks that happen, notionally, while the L1 block is the head of the chain. A state commitment that ignores them is faulty (and will be successfully challenged once fault challenges are finished). You can read more about this [in the specs](https://github.com/ethereum-optimism/optimism/blob/develop/specs/deposits.md).

2022-12-01 20:25 UTC, qbzzt commented on src/docs/protocol/README.md
> +With the OVM 2.0 upgrade, which happened on November 11th, 2021, the Optimism protocol went through its biggest upgrade to date. The primary focus of this upgrade was [EVM Equivalence](https://medium
Yes, but we don't need to do it yet. We'll change it when Bedrock is closer to being out.

2022-12-01 20:27 UTC, qbzzt commented
Thank you @norswap , I fixed most of the comments and asked clarifying questions where needed.

2022-12-03 19:07 UTC, norswap commented on src/docs/protocol/2-rollup-protocol.md
> +   Having the proof available for off-chain testing helps us guard against a whole class of vulnerabilities based on invalid fault proofs.
I think one thing that is confusing here is that withdrawal proofs should never be faulty, i.e. if they are, it means that either (1) we have a bug in our withdrawal proof system, or (2) the output root that they prove against is invalid.

I guess we could change to clarify:

> This new step enables off-chain monitoring of the withdrawals, which makes it easier to identify incorrect output roots, or bugs in the withdrawal system.

Also, this:

> Having the proof available for off-chain testing helps us guard against a whole class of vulnerabilities based on invalid fault proofs.

is not really accurate: there are actually no fault proofs no, and even if there were, I don't think it's related to this. Probably you meant "invalid withdrawal proofs"?

2022-12-03 19:08 UTC, norswap commented on src/docs/protocol/2-rollup-protocol.md
> +1. Wait for the next output root to be submitted to L1 (up to an hour on mainnet, less than that on the test network) then submit the withdrawal proof using `proveWithdrawalTransaction`.
@mslipper @protolambda

2022-12-03 19:17 UTC, norswap commented on src/docs/protocol/2-rollup-protocol.md
> +You can read more about this [in the specs](https://github.com/ethereum-optimism/optimism/blob/develop/specs/deposits.md).
It's correct, but I'm not sure everyone knows what "notionally" means, what about:

> Deposit transactions become part of the canonical blockchain in the first L2 block of the "epoch" corresponding to the L1 block where the deposits were made. This L2 block will usually be created a few minutes after the corresponding L1 block.

The relationship between the L1 and L2 head is rather complicated: there is the confirmation depth (responsible for the "few minutes" delay), and then the sequencer drift can further delay this. I wouldn't enter into the details here.

2022-12-03 19:25 UTC, norswap commented on src/docs/protocol/2-rollup-protocol.md
> +   You can read more about it [in the specs](https://github.com/ethereum-optimism/optimism/blob/develop/specs/exec-engine.md#happy-path-sync).
Okay, so there's three kinds of sync (this wasn't in my mind when I wrote the comment, so I understand why it's confusing):

1. Unsafe sync — this one is indeed mediated by the rollup-node. This is when you're up to date with the "canonical L2 chain" as derived from L1, but want to sync "unsafe L2 blocks" (not posted on L1 yet).
2. "Happy-path" sync (there's probably a better name for that) — when your node boots up after being down and you want don't want to reprocess the whole L2 history stored on L1: you just pick the latest L2 block hash from L1 and instruct the execution engine to sync up to that point. I'm not really sure how this is used in practice — I guess it could it could sync unsafe blocks as well as safe blocks if passed an unsafe L2 blockhash.
3. "Worst-case" sync — this is basically just deriving the chain from L1.

2022-12-03 19:32 UTC, norswap commented on src/docs/protocol/2-rollup-protocol.md
> +1. Transactions submitted on L1 (called *deposits* whether they have assets attached or not) have to be included by the sequencer in the Optimism block that starts the next epoch (in Optimism epoch i
Sorry I realized there's a markdown snafu here.

It shows
> `This is typically fast — about * 12s."`

But I wrote:

`This is typically fast — about <confirmation depth> * 12s."`
(html tags get elided)

I don't know the value of confirmation_depth, I asked on pod-client, will keep you posted if I get an answer. I would say "a few minutes" here as a placeholder that will be safe (might turn out to be better, e.g. 1 minute with a conf depth of 5).

2022-12-04 10:05 UTC, qbzzt commented on src/docs/protocol/2-rollup-protocol.md
> +1. Transactions submitted on L1 (called *deposits* whether they have assets attached or not) have to be included by the sequencer in the Optimism block that starts the next epoch (in Optimism epoch i
How about this?

> Transactions submitted on L1 (called *deposits* whether they have assets attached or not) are included in the chain in the appropriate L2 block.
>   Every L2 block is identified by the "epoch" (the L1 block to which it corresponds, which typically has happened a few minutes before the L2 block) and its serial number within that epoch.
>   The first block of the epoch includes all the deposits that happened in the L1 block to which it corresponds.

2022-12-04 10:14 UTC, qbzzt commented on src/docs/protocol/2-rollup-protocol.md
> +   Having the proof available for off-chain testing helps us guard against a whole class of vulnerabilities based on invalid fault proofs.
How about this?

> Wait for the next output root to be submitted to L1, then submit the withdrawal proof using `proveWithdrawalTransaction`. This new step enables off-chain verification of the withdrawals, which protects Optimism users against a whole class of potential bridge vulnerabilities.

2022-12-05 18:59 UTC, norswap commented on src/docs/protocol/2-rollup-protocol.md
> +1. Transactions submitted on L1 (called *deposits* whether they have assets attached or not) have to be included by the sequencer in the Optimism block that starts the next epoch (in Optimism epoch i
Yep, sounds good!

2022-12-05 19:00 UTC, norswap commented on src/docs/protocol/2-rollup-protocol.md
> +   Having the proof available for off-chain testing helps us guard against a whole class of vulnerabilities based on invalid fault proofs.
I like it a bit less, but I can definitely live with it :)

2022-12-05 20:41 UTC, protolambda commented on src/docs/protocol/2-rollup-protocol.md
> +1. Wait for the next output root to be submitted to L1 (up to an hour on mainnet, less than that on the test network) then submit the withdrawal proof using `proveWithdrawalTransaction`.
About an hour AFAIK. @smartcontracts made the last changes to the output root proposer interval configuration.

2022-12-09 15:21 UTC, Nicca42 commented
@qbzzt are these convos resolved? Please close them if they are.

2022-12-10 14:06 UTC, qbzzt commented on src/docs/protocol/2-rollup-protocol.md
> +1. Wait for the next output root to be submitted to L1 (up to an hour on mainnet, less than that on the test network) then submit the withdrawal proof using `proveWithdrawalTransaction`.
I told them to just use the SDK.

2022-12-10 14:08 UTC, qbzzt commented on src/docs/protocol/2-rollup-protocol.md
> +   You can read more about it [in the specs](https://github.com/ethereum-optimism/optimism/blob/develop/specs/exec-engine.md#happy-path-sync).
So what I wrote is accurate, I just need to make sure it's called "unsafe sync"?

2022-12-15 16:44 UTC, Nicca42 approved these changes

2022-12-15 16:45 UTC, Nicca42 commented
@norswap if you are happy please approve 😌

2022-12-16 13:53 UTC, merged