Update Proposer Section for Grants Council
ethereum-optimism/community-hub pull request #571
Opened 2022-12-21 19:45 UTC by justine-hy

Updating temporarily to let proposers know the process is changing due to the election of a Grants Council 

Another update will follow once the Grants Council has published a new grant proposal process

2022-12-21 21:44 UTC, qbzzt approved these changes

2022-12-22 13:29 UTC, Nicca42 requested changes
Spelling mistake

2022-12-22 13:29 UTC, Nicca42 commented on src/docs/governance/proposals.md
> +**You can expect grant proposals to begin begin processed again, via the Grants Council, January 26th.**
```suggestion
**You can expect grant proposals to begin being processed again via the Grants Council on January 26th.**
```

2022-12-22 13:29 UTC, Nicca42 approved these changes

2022-12-22 13:30 UTC, merged