Update Bedrock differences to latest info
ethereum-optimism/community-hub pull request #573
Opened 2022-12-22 07:18 UTC by mslipper

Updates the "How is Bedrock Different?" doc to reflect the latest information.

2022-12-22 13:39 UTC, Nicca42 requested changes

2022-12-22 13:39 UTC, Nicca42 commented on src/docs/developers/bedrock-temp/differences.md
> +
Can we remove this? not sure why it is in here.

2022-12-22 15:36 UTC, qbzzt commented on src/docs/developers/bedrock-temp/differences.md
> +
All our docs have these. It's the metadata.

2022-12-23 17:52 UTC, Nicca42 approved these changes

2022-12-23 17:52 UTC, merged