Page/fees explainer for users
ethereum-optimism/community-hub pull request #58
Opened 2021-04-05 18:25 UTC by platocrat

**Description**
First section for the User page!
Adding detailed "How Fees Work in Optimistic Ethereum" section.

**Metadata**
- Fixes #39

2021-04-08 17:45 UTC, snario commented on src/docs/users/fees-in-optimistic-ethereum.md
> +2. Complete a withdrawal (i.e. L2 → L1)
```suggestion
2. Complete a withdrawal (i.e., L2 → L1)
```
https://english.stackexchange.com/questions/6894/should-there-be-a-comma-after-i-e

2021-04-08 19:11 UTC, maurelian commented on src/.vuepress/config.js
> +        },
This comment pertains to line 83 below, and is unrelated to this PR. 

I had the impression that the `TLDR` page was removed. It's not on the current site, but it does appear in the [netlify preview link](https://deploy-preview-63--thirsty-swanson-df3e28.netlify.app/docs/) generated by the CI checks.

2021-04-08 20:34 UTC, maurelian requested changes
I left a lot of little nits here to address. 

More generally, I think the page needs to be a shorter, and more concise. As a reader looking for an answer to a specific question, I'm going to scroll up and down the whole page, and still won't really be sure where to look to get my answer.

I think the way to pare this down is to list out the questions we're trying to answer, and think about what needs to be on this page to answer those questions (and only those questions).

2021-04-08 20:34 UTC, maurelian commented on src/docs/users/fees-in-optimistic-ethereum.md
> +Two critical points to remember for this section here are: 1) you should never drop your `eth_gasPrice` or your transaction will simply get rejected on L2, and 2) never drop your `eth_estimateGas` `g
> never drop your `eth_estimateGas` `gasLimit` or your transaction might revert.

Do you mean, 'never drop `gasLimit` below the value returned by `eth_estimateGas`?

2021-04-08 20:34 UTC, maurelian commented on src/docs/users/fees-in-optimistic-ethereum.md
> +* **The `gasUsed` must always be under 9 million**.
```suggestion
* **`gasUsed` must always be under 9 million per transaction**.
```

2021-04-08 20:34 UTC, maurelian commented on src/docs/users/fees-in-optimistic-ethereum.md
> +* **The `gasUsed` must always be under 9 million**.
Similarly remove "The" from the following lines

2021-04-08 20:34 UTC, maurelian commented on src/docs/users/fees-in-optimistic-ethereum.md
> +* Lastly, **we add `executionGasUsed` as a new field in the transaction receipt.
```suggestion
* `gasPrice` is fixed as a constant (it is initially set to `1 Gwei`).
* `gasUsed` is always equal to the `gasLimit` (since 100% of gas is always used).
*  `executionGasUsed` is added as a new field in the transaction receipt.
```

No need to bold every line in a list.

2021-04-08 20:34 UTC, maurelian commented on src/docs/users/fees-in-optimistic-ethereum.md
> +There is a per transaction gas limit of 9 million in L2 and when you compile your contracts for L2, gas usage can increase by more than 5x.
```suggestion
There is a per transaction gas limit of 9 million on L2 and when you compile your contracts for L2, gas usage can increase by more than 5x.
```
We should be consistent in this phrasing

2021-04-08 20:34 UTC, maurelian commented on src/docs/users/fees-in-optimistic-ethereum.md
> +Nuisance gas is a separate subject from the kind the topics we covered above.
```suggestion
Nuisance gas is a separate subject from the topics we covered above.
```

2021-04-08 20:34 UTC, maurelian commented on src/docs/users/fees-in-optimistic-ethereum.md
> +**Nuisance gas exists to **provide an upper bound on the _maximum possible L1 gas_ that a [_fraud proof_](https://research.paradigm.xyz/optimism#fraud-proofs) can cost.**
```suggestion
Nuisance gas **provides an upper bound on the _maximum possible L1 gas_ that a [_fraud proof_](https://research.paradigm.xyz/optimism#fraud-proofs) can cost.**
```

2021-04-08 20:34 UTC, maurelian commented on src/docs/users/fees-in-optimistic-ethereum.md
> +### Main cost of a deposit
This section seems like it's trying to be a "how to read etherscan" tutorial. I assume it's motivated by previous attempts to answer certain questions, but it feels like it goes beyond the scope. I'd try to make it more concise by asking: 
1. What question are we trying to answer?
2. What information do we need to present here? 
3. What knowledge should we take as prerequisite (and provide links for users to gain that knowledge if they don't have it).

2021-04-08 20:39 UTC, platocrat commented on src/.vuepress/config.js
> +        },
I think that's because this branch is forked from the branch that re-adds the TL;DR page.

See this snapshot below of the commits shown above, in this PR.

<img width="717" alt="Screen Shot 2021-04-08 at 3 38 34 PM" src="https://user-images.githubusercontent.com/37757724/114093251-7de00000-9880-11eb-9b98-388e295c156e.png">

2021-04-08 21:14 UTC, platocrat commented on src/docs/users/fees-in-optimistic-ethereum.md
> +* **Transaction Action**: A concise explanation of the overall action that is being made in this transasction. You can use this field as a quick summary of the transaction details, excluding the fee
This is perfect, thanks!

2021-04-09 00:54 UTC, platocrat commented
> More generally, I think the page needs to be a shorter, and more concise. As a reader looking for an answer to a specific question, I'm going to scroll up and down the whole page, and still won't really be sure where to look to get my answer.
> 

> I think the way to pare this down is to list out the questions we're trying to answer, and think about what needs to be on this page to answer those questions (and only those questions).

I included your changes and cleaned up some stuff.
I also changed the headers into questions and bolded important text.

Both of these changes I think make the page easier to skim.

2021-04-09 02:09 UTC, snario commented
How is `executionPrice` decided?

2021-04-11 12:34 UTC, platocrat commented
@snario added a very brief section on this `executionPrice` variable.
Does this new section clarify?

2021-04-12 16:38 UTC, maurelian approved these changes
I made some suggestions, but go ahead and merge when you feel good about it.

2021-04-12 16:38 UTC, maurelian commented on src/docs/users/fees-in-optimistic-ethereum.md
> +Gas fees on L2 are charged in ETH (remember, [L2 ETH is not the same as ETH on L1](http://community.optimism.io/docs/protocol/evm-comparison.html#native-weth))
This should be https. 
Please use the relative linking format (ie. https://github.com/ethereum-optimism/community-hub/blob/159432ef32b0783422d4961ee9ba56c8df018999/src/docs/protocol/protocol.md#L49). That should also ensure https is used.

2021-04-12 16:38 UTC, maurelian commented on src/docs/users/fees-in-optimistic-ethereum.md
> +However, **the gas fee payment itself is equal to to your `gasLimit * gasPrice`**, a calculation that is slightly different from L1 where the fee you are charged is based on `gasUsed`.
I know I wanted to be more concise, but if the audience is users here, we should define each of these values.

2021-04-12 16:38 UTC, maurelian commented on src/docs/users/fees-in-optimistic-ethereum.md
> +rollupTxSize * dataPrice + executionPrice * gasUsed
Same for these valued: `rollupTxSize`, `dataPrice`, `executionPrice`

2021-04-12 16:38 UTC, maurelian commented on src/docs/users/fees-in-optimistic-ethereum.md
> +By reducing the size of your state variables, you will likely cut costs to reduce your `rollupTxSize` in exchange for increasing the amount of `gasUsed` for your transaction.
State variables or input variables? I'd assume the latter, but I'm not sure.

2021-04-12 16:38 UTC, maurelian commented on src/docs/users/fees-in-optimistic-ethereum.md
> +1. you should never drop your `eth_gasPrice` or your transaction will simply get rejected on L2, and
I think `reduce` is a better term than `drop`. Also 'drop from' what?

2021-04-12 16:38 UTC, maurelian commented on src/docs/users/fees-in-optimistic-ethereum.md
> +(Note, [ETH on L2 is actually WETH](http://community.optimism.io/docs/protocol/evm-comparison.html#native-weth), but we abstract this for you 🙂.)
please use relative link format.

2021-04-12 16:38 UTC, maurelian commented on src/docs/users/fees-in-optimistic-ethereum.md
> +(Note, [ETH on L2 is actually WETH](http://community.optimism.io/docs/protocol/evm-comparison.html#native-weth), but we abstract this for you 🙂.)
```suggestion
(Note, [ETH on L2 is actually WETH](http://community.optimism.io/docs/protocol/evm-comparison.html#native-weth), but we abstract this away for you 🙂.)
```

2021-04-12 16:38 UTC, maurelian commented on src/docs/users/fees-in-optimistic-ethereum.md
> +Next, if we look at the `Transaction Fee`, we can see that **this sender paid roughly `$78.42` for an SNX deposit to L2, a gas cost that you would expect for an L1 deposit.**
```suggestion
Next, if we look at the `Transaction Fee`, we can see that **this sender paid roughly `$78.42` for an SNX deposit to L2, a gas cost that you would expect for a somewhat complex L1 transaction.**
```

2021-04-12 16:40 UTC, platocrat commented on src/docs/protocol/evm-comparison.md
> +While some apps try to obviate the user experience (UX) of having to perform this ETH for WETH exchange/trade (e.g. Rarible does this quite well already), it still results in a suboptimal UX.
> Feels awkward calling out a project not everyone will be familiar with.

Should I remove this?

2021-04-12 16:41 UTC, platocrat commented on src/docs/protocol/evm-comparison.md
> +Users are still shown that WETH is being used, so the UX is _not completely_ rid of WETH.
> Unclear what you mean, where are users shown this?

Should I remove this?

2021-04-12 20:39 UTC, merged