feat(config): Add link to new decentralization post
ethereum-optimism/community-hub pull request #686
Opened 2023-03-14 03:21 UTC by qbzzt

2023-03-14 15:15 UTC, Nicca42 requested changes

2023-03-14 15:15 UTC, Nicca42 commented on src/.vuepress/config.js
> +          'htthttps://dev.optimism.io/decentralization-roadmap/',
```suggestion
          'https://dev.optimism.io/decentralization-roadmap/',
```

2023-03-14 17:57 UTC, qbzzt commented
Thank you and sorry - I really ought to avoid working while tired.

2023-03-20 15:16 UTC, Nicca42 approved these changes

2023-03-20 15:30 UTC, zainbacchus commented
Reopened here: https://github.com/ethereum-optimism/community-hub/pull/696

2023-03-20 15:33 UTC, Nicca42 commented
Closing for #696

2023-03-20 15:33 UTC, closed without merging