feat(*): Make the PBC vs. Foundation distinction clearer
ethereum-optimism/community-hub pull request #691
Opened 2023-03-17 19:30 UTC by qbzzt

Closing: DEVRL-765

2023-03-20 15:05 UTC, Nicca42 requested changes

2023-03-20 15:05 UTC, Nicca42 commented on src/docs/developers/bedrock/node-operator-guide.md
> +Do not attempt to use this in production prior to that upgrade. Keep an eye on these docs or [this Twitter account](https://twitter.com/OPLabsPBC) for announcements.
```suggestion
Do not attempt to use this in production prior to that upgrade. Keep an eye on these docs or [OP Lab's Twitter account](https://twitter.com/OPLabsPBC) for announcements.
```

2023-03-20 17:44 UTC, smartcontracts commented on src/docs/developers/bedrock/node-operator-guide.md
> +Do not attempt to use this in production prior to that upgrade. Keep an eye on these docs or [OP Lab's Twitter account](https://twitter.com/OPLabsPBC) for announcements.
```suggestion
Do not attempt to use this in production prior to that upgrade. Keep an eye on these docs or [the OP Labs Twitter account](https://twitter.com/OPLabsPBC) for announcements.
```

2023-03-20 17:44 UTC, smartcontracts commented on src/docs/developers/bedrock/upgrade-guide.md
> +Do not attempt to use this in production prior to that upgrade. Keep an eye on these docs or [OP Lab's Twitter account](https://twitter.com/OPLabsPBC) for announcements.
```suggestion
Do not attempt to use this in production prior to that upgrade. Keep an eye on these docs or [the OP Labs Twitter account](https://twitter.com/OPLabsPBC) for announcements.
```

2023-03-23 18:21 UTC, Nicca42 approved these changes

2023-03-23 18:21 UTC, merged