feat(protocol/deposit-flow): Low level documentation of bedrock deposit flow
ethereum-optimism/community-hub pull request #733
Opened 2023-05-12 19:16 UTC by qbzzt

Closing: DEVRL-840

2023-05-22 19:25 UTC, smartcontracts commented on src/docs/protocol/deposit-flow.md
> +In Optimism terminology *deposit* refers to any transaction that goes from L1 to L2.
```suggestion
In Optimism terminology, the term "*deposit transaction*" refers to any L2 transaction that is triggered by a transaction or event on L1.
```

2023-05-22 19:25 UTC, smartcontracts commented on src/docs/protocol/deposit-flow.md
> +1. An L1 entity, either a smart contract or an externally owned account (EOA), sends a deposit transaction to [`L1CrossDomainMessenger`](https://github.com/ethereum-optimism/optimism/blob/develop/pac
Maybe worth noting that an L1 account can call the `OptimismPortal` contract directly but will not be able to benefit from certain automatic safety protections and devex improvements.

2023-05-22 19:25 UTC, smartcontracts commented on src/docs/protocol/deposit-flow.md
> +   - `_message`, the L2 transaction's calldata, [formatted as per the ABI](https://docs.soliditylang.org/en/v0.8.19/abi-spec.html).
```suggestion
   - `_message`, the L2 transaction's calldata, formatted as per the [ABI](https://docs.soliditylang.org/en/v0.8.19/abi-spec.html) of the target account.
```

2023-05-22 19:25 UTC, smartcontracts commented on src/docs/protocol/deposit-flow.md
> +   - `_minGasLimit`, the gas limit required for the transaction on L2.
```suggestion
   - `_minGasLimit`, the minimum gas limit allowed for the transaction on L2. Note that this is a *minimum* and the actual amount provided on L2 may be higher (but never lower) than the specified gas limit.
```

2023-05-22 19:25 UTC, smartcontracts commented on src/docs/protocol/deposit-flow.md
> +   However, the L2 cross domain messenger does not revert when a replay fails due to low gas limit, it just emits a failure message.
Nit let's use `L2CrossDomainMessenger` (with backticks) instead of "L2 cross domain messenger".

2023-05-22 19:25 UTC, smartcontracts commented on src/docs/protocol/deposit-flow.md
> +![Overall process](../../assets/docs/protocol/deposit-flow/overall-process.svg)
Same comment as below re: maybe worth noting OptimismPortal direct access

2023-05-22 19:25 UTC, smartcontracts commented on src/docs/protocol/deposit-flow.md
> +   L2_CROSS_DOM_COMM=0x4200000000000000000000000000000000000007
```suggestion
   L2XDM_ADDRESS=0x4200000000000000000000000000000000000007
```

2023-05-22 19:25 UTC, smartcontracts commented on src/docs/protocol/deposit-flow.md
> +   L2_CROSS_DOM_COMM=0x4200000000000000000000000000000000000007
Maybe. But "COMM" doesn't fit here, it's `L2CrossDomainMessenger` and not `L2CrossDomainCommunicator`

2023-05-22 20:54 UTC, qbzzt commented on src/docs/protocol/deposit-flow.md
> +![Overall process](../../assets/docs/protocol/deposit-flow/overall-process.svg)
I prefer to leave the illustration as simple as possible (which is still somewhat complicated).

2023-05-30 21:10 UTC, refcell requested changes

2023-05-30 21:10 UTC, refcell commented on src/docs/protocol/deposit-flow.md
> +Deposits are transactions, and as such can fail due to several reasons:
Personally think it flows better keeping it simple:

```suggestion
Deposits transactions can fail due to several reasons:
```

2023-05-31 03:54 UTC, qbzzt commented on src/docs/protocol/deposit-flow.md
> +It is possible to replay a failed deposit, possibly with more gas,
It is, see below on exactly how to get it working.

2023-05-31 03:56 UTC, qbzzt commented
@refcell , I committed all the changes you suggested, do you want to check again?

2023-05-31 12:35 UTC, refcell approved these changes

2023-05-31 14:42 UTC, merged