feat(tx-fees): Update for bedrock's EIP 1559
ethereum-optimism/community-hub pull request #737
Opened 2023-05-17 20:51 UTC by qbzzt

Closing: DEVRL-940

2023-05-22 21:06 UTC, OPMattie reviewed
I'd like to keep more of this in Docs if we can rather than always link to github. 

Can you also add a page for 'Estimating Gas for Users' in the SDK section of docs? Right now that section just links back to this page.

https://github.com/ethereum-optimism/optimism-tutorial/tree/main/sdk-estimate-gas

imo this is more reference material than a tutorial, hence moving it to docs.

2023-05-30 19:05 UTC, K-Ho requested changes

2023-05-30 20:52 UTC, qbzzt commented on src/docs/developers/build/transaction-fees.md
> -Let's take a look at the two sources of cost in a transaction on Optimism: the L2 execution fee and the L1 data/security fee.
It seems to me redundant, but I'll add it back in.

2023-05-31 23:27 UTC, smartcontracts approved these changes

2023-06-02 20:20 UTC, merged