Add Sepolia dev docs
ethereum-optimism/community-hub pull request #880
Opened 2023-08-18 18:55 UTC by K-Ho

**Description**

Update docs to include initial sepolia info + how to run a sepolia node

2023-08-18 19:18 UTC, sbvegan requested changes

2023-08-18 19:18 UTC, sbvegan commented on src/docs/developers/bedrock/node-operator-guide.md
> +- `op-geth`: Minimum 4 CPUs, 8GB RAM. At least 32GB of storage is required for Goerli or Sepolia. At least 600GB of storage is required for mainnet. Storage must be SSD. Requirements are significantl
Lets bump the storage requirement up to 40GB for goerli.

2023-08-18 19:18 UTC, sbvegan commented on src/docs/developers/build/run-a-node.md
> +The next step is to download the data directory for `op-geth`. Note that for OP Sepolia, you do not need to donwload a data directory.
typo: download

2023-08-18 19:18 UTC, sbvegan commented on src/docs/useful-tools/networks.md
> +| Batch Inbox Address | [`0xff00000000000000000000000000000011155420`](https://sepolia.etherscan.io/address/0xff00000000000000000000000000000000000420)
Etherscan needs an updated address

2023-08-23 18:42 UTC, K-Ho commented on src/docs/developers/bedrock/node-operator-guide.md
> +1. **With a Genesis File:** This is used for testnets or deployments that are not migrated from a legacy network. In this case, you'll download the genesis file and initialize the data directory via
For "With a Genesis File" I would add explicitly - "This is for OP Sepolia, and other testnets or deployments...etc."

2023-08-23 18:42 UTC, K-Ho commented on src/docs/developers/bedrock/node-operator-guide.md
> +`op-geth` uses JSON files to encode a network's genesis information. Unlike OP Mainnet and Goerli, the genesis for Sepolia is not currently included in the `op-geth` binary. For networks that are ini
Would always specify "OP Goerli" and "OP Sepolia"

2023-08-23 18:42 UTC, K-Ho commented on src/docs/developers/build/run-a-node.md
> +1. **With a Genesis File:** This is used for testnets or deployments that are not migrated from a legacy network. In this case, you'll download the genesis file and initialize the data directory via
For "With a Genesis File" I would add explicitly - "This is for OP Sepolia, and other testnets or deployments...etc."

2023-08-23 18:42 UTC, K-Ho commented on src/docs/developers/build/run-a-node.md
> +If you're spinning up an OP Mainnet or Goerli node, use the [Initialization via Data Directory](#initialization-via-data-directory) path. If you're spinning up an OP Sepolia node, use the [Initializa
Always specify "OP Goerli" since Goerli is itself its own network

2023-08-23 18:42 UTC, K-Ho commented on src/docs/developers/build/run-a-node.md
> +`op-geth` uses JSON files to encode a network's genesis information. Unlike OP Mainnet and Goerli, the genesis for Sepolia is not currently included in the `op-geth` binary. For networks that are ini
OP Goerli, OP Sepolia

2023-08-23 20:06 UTC, sbvegan approved these changes

2023-08-23 20:06 UTC, merged