[Rework] Dockerless Node Running Rework
ethereum-optimism/community-hub pull request #882
Opened 2023-08-22 16:49 UTC by Hotmanics

**Description**

This is an attempt to streamline the "Running a node without Docker" process. 

There is now an "Intro" page that goes over system requirements and initial op-geth and op-node setup.
"Testnet" will run you through the process of setting up a node entirely through Goerli & Optimism Goerli.
"Mainnet"will run you through the process of setting up a node entirely through Ethereum Mainnet & Optimism Mainnet.

**Rationale**
The original implementation of these docs had combined both Testnet & Mainnet development into single instructions. Making the instructions unclear or making you take extra steps that are not necessary. You should be able to run through this PR's docs and follow the on-screen instructions to get EXACTLY the outcome you expect. There is less guesswork.
 
**Tests**

Ran through the docs and followed the instructions on my local machine several times to ensure instructions were clear and got you to a completed state.

2023-08-23 20:12 UTC, sbvegan commented
Hey @Hotmanics! Thanks for taking a crack at this reorganization, I won't have time to review until at least next week. In the meantime can you revert some of your linting changes (i.e. ' to ") so its easier to see what the changes are? Another general concern I'd like to flag is this may break some links to our docs and I want to be mindful of that. Just leaving it as a note here for now.

2023-08-31 20:06 UTC, Hotmanics commented
> Hey @Hotmanics! Thanks for taking a crack at this reorganization, I won't have time to review until at least next week. In the meantime can you revert some of your linting changes (i.e. ' to ") so its easier to see what the changes are? Another general concern I'd like to flag is this may break some links to our docs and I want to be mindful of that. Just leaving it as a note here for now.

Apologies I had not found time to revert those linting changes. Would you still like me to do so?

2023-08-31 20:46 UTC, sbvegan commented
@Hotmanics no problem, its actually fine! I'm going through and making some edits. I'll let you know when I'm done. I'll have someone at OP Labs review as well before we merge

2023-09-01 00:12 UTC, sbvegan commented
I'm going to do some more work on this tomorrow. I'm going to look at the testnet doc next, we need to add information around running an archive node, and OP Sepolia support that is a non-migrated network so it needs documentation around initializing via genesis file.

2023-09-15 21:11 UTC, K-Ho requested changes
AMAZING WORK!! What an awesome contribution that is already a massive improvement for the piece of docs that is currently causing the *most* developer pain and support issues. So glad to have you as part of the Collective @Hotmanics 🙏.

2023-09-15 21:11 UTC, K-Ho commented on src/docs/developers/nodes/mainnet.md
> +You will need to point `op-geth` at `l2geth` with `--rollup.historicalrpc`: Enables the historical RPC endpoint. This endpoint is used to fetch historical execution data from Legacy Geth. This flag i
```suggestion
You will need to point `op-geth` at `l2geth` with `--rollup.historicalrpc`: Enables the historical RPC endpoint. This endpoint is used to fetch historical execution data from Legacy Geth from before the [Bedrock upgrade](https://twitter.com/optimismFND/status/1666850591669202965). This flag is only necessary for OP Mainnet.
```

2023-09-15 21:11 UTC, K-Ho commented on src/docs/developers/nodes/intro.md
> +### (Optional - Archive Node) Build l2geth
Specify this is *only* needed for OP Mainnet, not OP Sepolia.

2023-09-15 21:11 UTC, K-Ho commented on src/docs/developers/nodes/mainnet.md
> +#### (Optional - Archive Node) Get the data directory for `l2geth`
Only for OP Mainnet

2023-09-15 21:11 UTC, K-Ho commented on src/docs/developers/nodes/mainnet.md
> +::: info Snapshots
What is the actionable here? Is there a flag recommended to be set? I think this just adds confusion unless there is an actionable.

2023-09-15 21:11 UTC, K-Ho commented on src/docs/developers/nodes/mainnet.md
> +- Change `<< URL to L1 >>` to your local L1 node or a service provider's URL for the L1 node (L1 Ethereum).
provide an example: "E.g. for Infura, 1https://mainnet.infura.io/v3/API_KEY`"

2023-09-15 21:11 UTC, K-Ho commented on src/docs/developers/nodes/mainnet.md
> +4. Insert this snippet of code into `run-estimate.sh`:
This is a bit messy to have in our docs, can't we instead put this in a repo somewhere and let them clone it? I don't like the idea of copy and pasting huge scripts from our docs

2023-09-15 21:11 UTC, K-Ho commented on src/docs/developers/nodes/testnet.md
> +Migrated Networks, *OP Mainnet* and *OP Goerli*, were running before the Bedrock upgrade. Non-Migrated Networks, *OP Sepolia*, have only existed in a post Bedrock world. The way transaction execution
I think we can honestly just remove all mentions of OP Goerli at this point. Everyone should start using OP Sepolia right now.

2023-09-15 21:11 UTC, K-Ho commented on src/docs/developers/nodes/testnet.md
> +## OP Goerli initialization
Honestly think we should just remove mentions of OP Goerli, or maybe put it in a less visible, seperate section.

2023-09-15 21:11 UTC, K-Ho commented on src/docs/developers/nodes/testnet.md
> +#### (Optional - Archive Node) Get the data directory for `l2geth`
Only for Goerli, think we should be good to remove this imo

2023-09-15 21:11 UTC, K-Ho commented on src/docs/developers/nodes/testnet.md
> +- Change `<< URL to L1 >>` to a service provider's URL for the L1 network (L1 Goerli or Sepolia).
Give an example like I suggested in mainnet guide

2023-09-15 21:11 UTC, K-Ho commented on src/docs/developers/nodes/testnet.md
> +- Change `<< URL to L1 >>` to a service provider's URL for the L1 network (L1 Goerli or Sepolia).
for context, we've often had users misparameterize this (e.g. to point to an L2 node)

2023-09-15 21:11 UTC, K-Ho commented on src/docs/developers/nodes/testnet.md
> +1. Navigate to your `scripts` directory
Same comment as for mainnet guide, let's put this in a repo somewhere

2023-09-18 21:10 UTC, sbvegan commented on src/docs/developers/nodes/intro.md
> +Replicas need to store the transaction history of OP Mainnet (or the relevant OP testnet) and to run Geth. They need to be relatively powerful machines (real or virtual). We recommend at least 16 GB
I'm going to leave this one open because I'm not sure of the requirements for OP Sepolia

2023-09-25 16:48 UTC, refcell commented on src/docs/developers/build/run-a-node.md
> -
If we delete this file, there are a few places that need to be updated to point to the new docs.

- https://github.com/Hotmanics/community-hub/blob/running-a-node-rework/src/docs/developers/README.md?plain=1#L28
- https://github.com/Hotmanics/community-hub/blob/running-a-node-rework/src/docs/guides/wallet-dev.md?plain=1#L16
- https://github.com/Hotmanics/community-hub/blob/running-a-node-rework/src/docs/developers/bridge/comm-strategies.md?plain=1#L14
- https://github.com/Hotmanics/community-hub/blob/running-a-node-rework/src/docs/contribute/contribution-path/techNERDs.md?plain=1#L23

2023-09-25 16:48 UTC, refcell commented on src/docs/developers/nodes/mainnet.md
> +4. Insert this snippet of code into `run-estimate.sh`:
I think since this step is just for estimating sync time, it's ok to remove later.

2023-09-25 16:48 UTC, refcell commented on src/docs/developers/nodes/testnet.md
> +:::
We shouldn't need this since the guide is for op-sepolia.

2023-09-28 21:38 UTC, sbvegan commented on src/docs/developers/build/run-a-node.md
> -
Good catch, I'll add a redirect

2023-09-28 21:41 UTC, sbvegan approved these changes

2023-09-28 21:43 UTC, sbvegan approved these changes

2023-09-28 21:45 UTC, merged