demo doc updated
ethereum-optimism/community-hub pull request #991
Opened 2024-01-26 20:16 UTC by JrockiBedrock

updated demo day doc to reflect current demo day process

2024-01-29 16:16 UTC, Nicca42 requested changes

2024-01-29 16:16 UTC, Nicca42 commented on src/docs/contribute/demo-day.md
> +1. Your dApp deployed & **live on Optimism**
Can we update this to live on OP Mainnet

2024-01-29 21:38 UTC, JrockiBedrock commented on src/docs/contribute/demo-day.md
> +1. Your dApp deployed & **live on Optimism**
updated language "live on Optimism" -->  "live on OP Mainnet"

2024-01-30 17:26 UTC, Nicca42 approved these changes

2024-01-30 17:27 UTC, Nicca42 requested changes

2024-01-30 17:27 UTC, Nicca42 commented on src/docs/contribute/demo-day.md
> +For further visibility projects are encouraged to add their project into our developers show and tell section here on [GitHub] https://github.com/ethereum-optimism/developers/discussions/categories/s
This formatting is broken

2024-02-01 20:58 UTC, JrockiBedrock commented on src/docs/contribute/demo-day.md
> +For further visibility projects are encouraged to add their project into our developers show and tell section here on [GitHub] https://github.com/ethereum-optimism/developers/discussions/categories/s
just pushed the fix

2024-02-07 18:44 UTC, Nicca42 approved these changes

2024-02-07 18:44 UTC, merged